/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unical.pos.view.inventory.inventory;

import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JDesktopPane;
import net.unical.pos.view.configarations.PaymentTypes;
import net.unical.pos.view.configarations.PrinterTypes;
import net.unical.pos.view.configarations.UnitTypes;
import net.unical.pos.view.home.Dashboard;
import net.unical.pos.view.inventory.store.GoodReceiveNote;
import net.unical.pos.view.inventory.store.GoodReceiveNoteList;
import net.unical.pos.view.inventory.store.PurchaseOrder;
import net.unical.pos.view.inventory.store.PurchaseOrderList;
import net.unical.pos.view.inventory.store.StockLocation;
import net.unical.pos.view.inventory.store.StockManagement;
import net.unical.pos.view.inventory.store.SupplierManagement;


/**
 *
 * @author Sanjuka
 */
public class Inventory extends javax.swing.JInternalFrame {

    /**
     * Creates new form Inventory
     */
    Dashboard dashboard;
    
    public Inventory(Dashboard dashboard) {
        this.setTitle("Inventory");
        this.dashboard=dashboard; 
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel13 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        itemListBtn = new org.jdesktop.swingx.JXButton();
        mainItemBtn = new org.jdesktop.swingx.JXButton();
        mainItemCategoryBtn = new org.jdesktop.swingx.JXButton();
        subItemCategoryBtn = new org.jdesktop.swingx.JXButton();
        jPanel3 = new javax.swing.JPanel();
        poBtn = new org.jdesktop.swingx.JXButton();
        poListBtn = new org.jdesktop.swingx.JXButton();
        grnBtn = new org.jdesktop.swingx.JXButton();
        grnListBtn = new org.jdesktop.swingx.JXButton();
        stockBtn = new org.jdesktop.swingx.JXButton();
        supplierBtn = new org.jdesktop.swingx.JXButton();
        stockLocationBtn = new org.jdesktop.swingx.JXButton();
        stockTransferBtn = new org.jdesktop.swingx.JXButton();
        jPanel4 = new javax.swing.JPanel();
        jXButton5 = new org.jdesktop.swingx.JXButton();
        jXButton6 = new org.jdesktop.swingx.JXButton();
        jXButton7 = new org.jdesktop.swingx.JXButton();
        jXButton16 = new org.jdesktop.swingx.JXButton();
        jXButton17 = new org.jdesktop.swingx.JXButton();
        jXButton18 = new org.jdesktop.swingx.JXButton();

        jLabel13.setBackground(new java.awt.Color(0, 102, 153));
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Stock Transfer ");
        jLabel13.setOpaque(true);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Inventory", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        itemListBtn.setBackground(new java.awt.Color(0, 102, 153));
        itemListBtn.setForeground(new java.awt.Color(255, 255, 255));
        itemListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/mainItems-35.png"))); // NOI18N
        itemListBtn.setText("Item List");
        itemListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        itemListBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        itemListBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                itemListBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                itemListBtnMouseExited(evt);
            }
        });
        itemListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemListBtnActionPerformed(evt);
            }
        });

        mainItemBtn.setBackground(new java.awt.Color(0, 102, 153));
        mainItemBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainItemBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/addNew-35.png"))); // NOI18N
        mainItemBtn.setText("New Item");
        mainItemBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        mainItemBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mainItemBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainItemBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainItemBtnMouseExited(evt);
            }
        });
        mainItemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainItemBtnActionPerformed(evt);
            }
        });

        mainItemCategoryBtn.setBackground(new java.awt.Color(0, 102, 153));
        mainItemCategoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        mainItemCategoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/mainItemCategory-35.png"))); // NOI18N
        mainItemCategoryBtn.setText("Main Category");
        mainItemCategoryBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        mainItemCategoryBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        mainItemCategoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                mainItemCategoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                mainItemCategoryBtnMouseExited(evt);
            }
        });
        mainItemCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainItemCategoryBtnActionPerformed(evt);
            }
        });

        subItemCategoryBtn.setBackground(new java.awt.Color(0, 102, 153));
        subItemCategoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        subItemCategoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/subItemCategory-35.png"))); // NOI18N
        subItemCategoryBtn.setText("Sub Category");
        subItemCategoryBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEADING);
        subItemCategoryBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        subItemCategoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                subItemCategoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                subItemCategoryBtnMouseExited(evt);
            }
        });
        subItemCategoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subItemCategoryBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subItemCategoryBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainItemBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(itemListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(mainItemCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainItemCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(subItemCategoryBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(mainItemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(itemListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Store", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel3.setForeground(new java.awt.Color(255, 255, 255));

        poBtn.setBackground(new java.awt.Color(0, 102, 153));
        poBtn.setForeground(new java.awt.Color(255, 255, 255));
        poBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/icons8-purchase-order-35.png"))); // NOI18N
        poBtn.setText("Purchase Order");
        poBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        poBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                poBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                poBtnMouseExited(evt);
            }
        });
        poBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poBtnActionPerformed(evt);
            }
        });

        poListBtn.setBackground(new java.awt.Color(0, 102, 153));
        poListBtn.setForeground(new java.awt.Color(255, 255, 255));
        poListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/icons8-purchase-order-list-35.png"))); // NOI18N
        poListBtn.setText("Purchase Order List");
        poListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        poListBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                poListBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                poListBtnMouseExited(evt);
            }
        });
        poListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poListBtnActionPerformed(evt);
            }
        });

        grnBtn.setBackground(new java.awt.Color(0, 102, 153));
        grnBtn.setForeground(new java.awt.Color(255, 255, 255));
        grnBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/grn-35.png"))); // NOI18N
        grnBtn.setText("Good Receive Note");
        grnBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grnBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grnBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grnBtnMouseExited(evt);
            }
        });
        grnBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnBtnActionPerformed(evt);
            }
        });

        grnListBtn.setBackground(new java.awt.Color(0, 102, 153));
        grnListBtn.setForeground(new java.awt.Color(255, 255, 255));
        grnListBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/grn-list-35.png"))); // NOI18N
        grnListBtn.setText("GRN List");
        grnListBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        grnListBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                grnListBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                grnListBtnMouseExited(evt);
            }
        });
        grnListBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grnListBtnActionPerformed(evt);
            }
        });

        stockBtn.setBackground(new java.awt.Color(0, 102, 153));
        stockBtn.setForeground(new java.awt.Color(255, 255, 255));
        stockBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/stock-35.png"))); // NOI18N
        stockBtn.setText("Stock Management");
        stockBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stockBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockBtnMouseExited(evt);
            }
        });
        stockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockBtnActionPerformed(evt);
            }
        });

        supplierBtn.setBackground(new java.awt.Color(0, 102, 153));
        supplierBtn.setForeground(new java.awt.Color(255, 255, 255));
        supplierBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/icons8-supplier-35.png"))); // NOI18N
        supplierBtn.setText("Supplier Management");
        supplierBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        supplierBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                supplierBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                supplierBtnMouseExited(evt);
            }
        });
        supplierBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supplierBtnActionPerformed(evt);
            }
        });

        stockLocationBtn.setBackground(new java.awt.Color(0, 102, 153));
        stockLocationBtn.setForeground(new java.awt.Color(255, 255, 255));
        stockLocationBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/stock location-update-35.png"))); // NOI18N
        stockLocationBtn.setText("Stock Location ");
        stockLocationBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stockLocationBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockLocationBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockLocationBtnMouseExited(evt);
            }
        });
        stockLocationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockLocationBtnActionPerformed(evt);
            }
        });

        stockTransferBtn.setBackground(new java.awt.Color(0, 102, 153));
        stockTransferBtn.setForeground(new java.awt.Color(255, 255, 255));
        stockTransferBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/icons8-transfer-35.png"))); // NOI18N
        stockTransferBtn.setText("Stock Transfer ");
        stockTransferBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        stockTransferBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                stockTransferBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                stockTransferBtnMouseExited(evt);
            }
        });
        stockTransferBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stockTransferBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(10, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supplierBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grnListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(grnBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(poListBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(poBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockLocationBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockTransferBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(poListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(grnBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grnListBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(supplierBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockLocationBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(stockTransferBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Settiings", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel4.setForeground(new java.awt.Color(255, 255, 255));

        jXButton5.setBackground(new java.awt.Color(0, 102, 153));
        jXButton5.setForeground(new java.awt.Color(255, 255, 255));
        jXButton5.setText("Config Tables");
        jXButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jXButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton5ActionPerformed(evt);
            }
        });

        jXButton6.setBackground(new java.awt.Color(0, 102, 153));
        jXButton6.setForeground(new java.awt.Color(255, 255, 255));
        jXButton6.setText("Sub Table Location");
        jXButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jXButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton6ActionPerformed(evt);
            }
        });

        jXButton7.setBackground(new java.awt.Color(0, 102, 153));
        jXButton7.setForeground(new java.awt.Color(255, 255, 255));
        jXButton7.setText("Main Table Location");
        jXButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jXButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton7ActionPerformed(evt);
            }
        });

        jXButton16.setBackground(new java.awt.Color(0, 102, 153));
        jXButton16.setForeground(new java.awt.Color(255, 255, 255));
        jXButton16.setText("Unit Typs");
        jXButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton16ActionPerformed(evt);
            }
        });

        jXButton17.setBackground(new java.awt.Color(0, 102, 153));
        jXButton17.setForeground(new java.awt.Color(255, 255, 255));
        jXButton17.setText("Payment Typs");
        jXButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton17ActionPerformed(evt);
            }
        });

        jXButton18.setBackground(new java.awt.Color(0, 102, 153));
        jXButton18.setForeground(new java.awt.Color(255, 255, 255));
        jXButton18.setText("Printer Typs");
        jXButton18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton18ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jXButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jXButton17, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXButton18, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jXButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jXButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemListBtnActionPerformed
        ItemList itemList = new ItemList(dashboard);
        dashboard.desktopPane.add(itemList);
        Dimension d = dashboard.desktopPane.getSize();
        itemList.setLayer(JDesktopPane.POPUP_LAYER);
        itemList.setSize(d);
        itemList.setVisible(true);
    }//GEN-LAST:event_itemListBtnActionPerformed

    private void mainItemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainItemBtnActionPerformed
        MainItem newItem = new MainItem(false,0);
        dashboard.desktopPane.add(newItem);
        Dimension d = dashboard.desktopPane.getSize();
        newItem.setLayer(JDesktopPane.POPUP_LAYER);
        newItem.setSize(d);
        newItem.setVisible(true);
    }//GEN-LAST:event_mainItemBtnActionPerformed

    private void subItemCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subItemCategoryBtnActionPerformed
        SubCategory subCategory = new SubCategory(dashboard);
        dashboard.desktopPane.add(subCategory);
        Dimension d = dashboard.desktopPane.getSize();
        subCategory.setLayer(JDesktopPane.POPUP_LAYER);
        subCategory.setSize(d);
        subCategory.setVisible(true);
    }//GEN-LAST:event_subItemCategoryBtnActionPerformed

    private void mainItemCategoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainItemCategoryBtnActionPerformed
        MainCategory mainCategory = new MainCategory(dashboard);
        dashboard.desktopPane.add(mainCategory);
        Dimension d = dashboard.desktopPane.getSize();
        mainCategory.setLayer(JDesktopPane.POPUP_LAYER);
        mainCategory.setSize(d);
        mainCategory.setVisible(true);
    }//GEN-LAST:event_mainItemCategoryBtnActionPerformed

    private void jXButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton5ActionPerformed
        ConfigTables configTables = new ConfigTables(dashboard);
        dashboard.desktopPane.add(configTables);
        Dimension d = dashboard.desktopPane.getSize();
        configTables.setLayer(JDesktopPane.POPUP_LAYER);
        configTables.setSize(d);
        configTables.setVisible(true);
    }//GEN-LAST:event_jXButton5ActionPerformed

    private void jXButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton6ActionPerformed
        SubTableLocation subTableLocation = new SubTableLocation(dashboard);
        dashboard.desktopPane.add(subTableLocation);
        Dimension d = dashboard.desktopPane.getSize();
        subTableLocation.setLayer(JDesktopPane.POPUP_LAYER);
        subTableLocation.setSize(d);
        subTableLocation.setVisible(true);
    }//GEN-LAST:event_jXButton6ActionPerformed

    private void jXButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton7ActionPerformed
        MainTableLocation mainTableLocation = new MainTableLocation(dashboard);
        dashboard.desktopPane.add(mainTableLocation);
        Dimension d = dashboard.desktopPane.getSize();
        mainTableLocation.setLayer(JDesktopPane.POPUP_LAYER);
        mainTableLocation.setSize(d);
        mainTableLocation.setVisible(true);
    }//GEN-LAST:event_jXButton7ActionPerformed

    private void poBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poBtnActionPerformed
        PurchaseOrder purchaseOrder = new PurchaseOrder(dashboard);
        dashboard.desktopPane.add(purchaseOrder);
        Dimension d = dashboard.desktopPane.getSize();
        purchaseOrder.setLayer(JDesktopPane.POPUP_LAYER);
        purchaseOrder.setSize(d);
        purchaseOrder.setVisible(true);
    }//GEN-LAST:event_poBtnActionPerformed

    private void poListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poListBtnActionPerformed
        PurchaseOrderList purchaseOrderList = new PurchaseOrderList(dashboard);
        dashboard.desktopPane.add(purchaseOrderList);
        Dimension d = dashboard.desktopPane.getSize();
        purchaseOrderList.setLayer(JDesktopPane.POPUP_LAYER);
        purchaseOrderList.setSize(d);
        purchaseOrderList.setVisible(true);
    }//GEN-LAST:event_poListBtnActionPerformed

    private void grnBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnBtnActionPerformed
        GoodReceiveNote goodReceiveNote = new GoodReceiveNote(dashboard);
        dashboard.desktopPane.add(goodReceiveNote);
        Dimension d = dashboard.desktopPane.getSize();
        goodReceiveNote.setLayer(JDesktopPane.POPUP_LAYER);
        goodReceiveNote.setSize(d);
        goodReceiveNote.setVisible(true);
    }//GEN-LAST:event_grnBtnActionPerformed

    private void grnListBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grnListBtnActionPerformed
        GoodReceiveNoteList goodReceiveNoteList = new GoodReceiveNoteList(dashboard);
        dashboard.desktopPane.add(goodReceiveNoteList);
        Dimension d = dashboard.desktopPane.getSize();
        goodReceiveNoteList.setLayer(JDesktopPane.POPUP_LAYER);
        goodReceiveNoteList.setSize(d);
        goodReceiveNoteList.setVisible(true);
    }//GEN-LAST:event_grnListBtnActionPerformed

    private void stockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockBtnActionPerformed
        StockManagement stockManagement = new StockManagement(dashboard);
        dashboard.desktopPane.add(stockManagement);
        Dimension d = dashboard.desktopPane.getSize();
        stockManagement.setLayer(JDesktopPane.POPUP_LAYER);
        stockManagement.setSize(d);
        stockManagement.setVisible(true);
    }//GEN-LAST:event_stockBtnActionPerformed

    private void supplierBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supplierBtnActionPerformed
        SupplierManagement supplierManagement = new SupplierManagement(dashboard);
        dashboard.desktopPane.add(supplierManagement);
        Dimension d = dashboard.desktopPane.getSize();
        supplierManagement.setLayer(JDesktopPane.POPUP_LAYER);
        supplierManagement.setSize(d);
        supplierManagement.setVisible(true);
    }//GEN-LAST:event_supplierBtnActionPerformed

    private void stockLocationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockLocationBtnActionPerformed
        StockLocation stockLocation = new StockLocation(dashboard);
        dashboard.desktopPane.add(stockLocation);
        Dimension d = dashboard.desktopPane.getSize();
        stockLocation.setLayer(JDesktopPane.POPUP_LAYER);
        stockLocation.setSize(d);
        stockLocation.setVisible(true);
    }//GEN-LAST:event_stockLocationBtnActionPerformed

    private void stockTransferBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stockTransferBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stockTransferBtnActionPerformed

    private void jXButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton16ActionPerformed
        UnitTypes unitTypes = new UnitTypes(dashboard);
        dashboard.desktopPane.add(unitTypes);
        Dimension d = dashboard.desktopPane.getSize();
        unitTypes.setLayer(JDesktopPane.POPUP_LAYER);
        unitTypes.setSize(d);
        unitTypes.setVisible(true);
    }//GEN-LAST:event_jXButton16ActionPerformed

    private void mainItemCategoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainItemCategoryBtnMouseEntered
        mainItemCategoryBtn.setBackground(new Color(11,125,182));
        mainItemCategoryBtn.setVisible(true);
    }//GEN-LAST:event_mainItemCategoryBtnMouseEntered

    private void subItemCategoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subItemCategoryBtnMouseEntered
        subItemCategoryBtn.setBackground(new Color(11,125,182));
        subItemCategoryBtn.setVisible(true);
    }//GEN-LAST:event_subItemCategoryBtnMouseEntered

    private void mainItemBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainItemBtnMouseEntered
        mainItemBtn.setBackground(new Color(11,125,182));
        mainItemBtn.setVisible(true);
    }//GEN-LAST:event_mainItemBtnMouseEntered

    private void itemListBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListBtnMouseEntered
        itemListBtn.setBackground(new Color(11,125,182));
        itemListBtn.setVisible(true);
    }//GEN-LAST:event_itemListBtnMouseEntered

    private void poBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poBtnMouseEntered
        poBtn.setBackground(new Color(11,125,182));
        poBtn.setVisible(true);
    }//GEN-LAST:event_poBtnMouseEntered

    private void poListBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poListBtnMouseEntered
        poListBtn.setBackground(new Color(11,125,182));
        poListBtn.setVisible(true);
    }//GEN-LAST:event_poListBtnMouseEntered

    private void grnBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grnBtnMouseEntered
        grnBtn.setBackground(new Color(11,125,182));
        grnBtn.setVisible(true);
    }//GEN-LAST:event_grnBtnMouseEntered

    private void grnListBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grnListBtnMouseEntered
        grnListBtn.setBackground(new Color(11,125,182));
        grnListBtn.setVisible(true);
    }//GEN-LAST:event_grnListBtnMouseEntered

    private void stockBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockBtnMouseEntered
        stockBtn.setBackground(new Color(11,125,182));
        stockBtn.setVisible(true);
    }//GEN-LAST:event_stockBtnMouseEntered

    private void supplierBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtnMouseEntered
        supplierBtn.setBackground(new Color(11,125,182));
        supplierBtn.setVisible(true);
    }//GEN-LAST:event_supplierBtnMouseEntered

    private void stockLocationBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockLocationBtnMouseEntered
        stockLocationBtn.setBackground(new Color(11,125,182));
        stockLocationBtn.setVisible(true);
    }//GEN-LAST:event_stockLocationBtnMouseEntered

    private void stockTransferBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTransferBtnMouseEntered
        stockTransferBtn.setBackground(new Color(11,125,182));
        stockTransferBtn.setVisible(true);
    }//GEN-LAST:event_stockTransferBtnMouseEntered

    private void mainItemCategoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainItemCategoryBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_mainItemCategoryBtnMouseExited

    private void subItemCategoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_subItemCategoryBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_subItemCategoryBtnMouseExited

    private void mainItemBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mainItemBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_mainItemBtnMouseExited

    private void itemListBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemListBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_itemListBtnMouseExited

    private void poBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_poBtnMouseExited

    private void poListBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_poListBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_poListBtnMouseExited

    private void grnBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grnBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_grnBtnMouseExited

    private void grnListBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grnListBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_grnListBtnMouseExited

    private void stockBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_stockBtnMouseExited

    private void supplierBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_supplierBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_supplierBtnMouseExited

    private void stockLocationBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockLocationBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_stockLocationBtnMouseExited

    private void stockTransferBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_stockTransferBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_stockTransferBtnMouseExited

    private void jXButton17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton17ActionPerformed
        PaymentTypes paymentTypes = new PaymentTypes(dashboard);
        dashboard.desktopPane.add(paymentTypes);
        Dimension d = dashboard.desktopPane.getSize();
        paymentTypes.setLayer(JDesktopPane.POPUP_LAYER);
        paymentTypes.setSize(d);
        paymentTypes.setVisible(true);
    }//GEN-LAST:event_jXButton17ActionPerformed

    private void jXButton18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton18ActionPerformed
        PrinterTypes printerTypes = new PrinterTypes(dashboard);
        dashboard.desktopPane.add(printerTypes);
        Dimension d = dashboard.desktopPane.getSize();
        printerTypes.setLayer(JDesktopPane.POPUP_LAYER);
        printerTypes.setSize(d);
        printerTypes.setVisible(true);
    }//GEN-LAST:event_jXButton18ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Inventory.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Inventory().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton grnBtn;
    private org.jdesktop.swingx.JXButton grnListBtn;
    private org.jdesktop.swingx.JXButton itemListBtn;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private org.jdesktop.swingx.JXButton jXButton16;
    private org.jdesktop.swingx.JXButton jXButton17;
    private org.jdesktop.swingx.JXButton jXButton18;
    private org.jdesktop.swingx.JXButton jXButton5;
    private org.jdesktop.swingx.JXButton jXButton6;
    private org.jdesktop.swingx.JXButton jXButton7;
    private org.jdesktop.swingx.JXButton mainItemBtn;
    private org.jdesktop.swingx.JXButton mainItemCategoryBtn;
    private org.jdesktop.swingx.JXButton poBtn;
    private org.jdesktop.swingx.JXButton poListBtn;
    private org.jdesktop.swingx.JXButton stockBtn;
    private org.jdesktop.swingx.JXButton stockLocationBtn;
    private org.jdesktop.swingx.JXButton stockTransferBtn;
    private org.jdesktop.swingx.JXButton subItemCategoryBtn;
    private org.jdesktop.swingx.JXButton supplierBtn;
    // End of variables declaration//GEN-END:variables

    private void btnBackgroundExit(){
        mainItemCategoryBtn.setBackground(new Color(0,102,153));
        subItemCategoryBtn.setBackground(new Color(0,102,153));
        mainItemBtn.setBackground(new Color(0,102,153));
        itemListBtn.setBackground(new Color(0,102,153));
        poBtn.setBackground(new Color(0,102,153));
        poListBtn.setBackground(new Color(0,102,153));    
        grnBtn.setBackground(new Color(0,102,153));    
        grnListBtn.setBackground(new Color(0,102,153));    
        stockBtn.setBackground(new Color(0,102,153));    
        supplierBtn.setBackground(new Color(0,102,153));    
        stockLocationBtn.setBackground(new Color(0,102,153));    
        stockTransferBtn.setBackground(new Color(0,102,153));    
    }
}
