/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unical.pos.view.employee;

import java.awt.Color;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.unical.pos.configurations.ConfigTimer;
import net.unical.pos.controller.EmployeeManagementController;
import net.unical.pos.controller.UserAccountManagementController;
import net.unical.pos.controller.UserRoleController;
import net.unical.pos.dto.EmployeeManagementDto;
import net.unical.pos.dto.UserDto;
import net.unical.pos.dto.UserRoleDto;
import net.unical.pos.view.home.Dashboard;
import org.springframework.security.crypto.bcrypt.BCrypt;

/**
 *
 * @author Sanjuka
 */
public class UserAccountManagement extends javax.swing.JInternalFrame {

    /**
     * Creates new form UserAccountManagement
     */
    
    private boolean update=false;
    
    private UserAccountManagementController userAcountManagementController;
    private EmployeeManagementController employeeManagementController;
    private UserRoleController userRoleController;
    private ConfigTimer configTimer;
    
    private ArrayList<Integer> employeeIds=new ArrayList<>();
    private ArrayList<Integer> userRoleIds=new ArrayList<>();
    
    public UserAccountManagement(Dashboard dashboard) {
        initComponents();
        
        this.userAcountManagementController=new UserAccountManagementController();
        this.employeeManagementController=new EmployeeManagementController();
        this.userRoleController=new UserRoleController();
        
        this.configTimer=new ConfigTimer();
        
        loadAllUsers();
        loadEmployees();
        loadUserRole();
        jLabel6.setText("<html>Note: Only enter the new password in the password field<br>if you need to change the password.<br>Otherwise, leave the password field blank.</html>");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        messageLbl = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        employeeCmb = new javax.swing.JComboBox<>();
        userRoleCmb = new javax.swing.JComboBox<>();
        userNameTxt = new org.jdesktop.swingx.JXTextField();
        passwordTxt = new javax.swing.JPasswordField();
        clearBtn = new org.jdesktop.swingx.JXButton();
        isActiveBox = new javax.swing.JCheckBox();
        saveBtn = new org.jdesktop.swingx.JXButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userDetailsTbl = new org.jdesktop.swingx.JXTable();

        messageLbl.setBackground(new java.awt.Color(0, 153, 0));
        messageLbl.setForeground(new java.awt.Color(255, 255, 255));
        messageLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        messageLbl.setOpaque(true);

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User Account", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel1.setText("Employee");

        jLabel2.setText("User Role");

        jLabel3.setText("User Name");

        jLabel4.setText("Password");

        clearBtn.setBackground(new java.awt.Color(204, 204, 0));
        clearBtn.setText("Clear");
        clearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBtnActionPerformed(evt);
            }
        });

        isActiveBox.setSelected(true);
        isActiveBox.setText("Is Active");

        saveBtn.setBackground(new java.awt.Color(0, 102, 153));
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        jLabel6.setForeground(new java.awt.Color(204, 0, 0));
        jLabel6.setText("Note: Only enter the new password in the password field if you need to change the password. Otherwise, leave the password field blank.");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(85, 85, 85))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(employeeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userRoleCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(passwordTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(isActiveBox, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(199, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(employeeCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userRoleCmb))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passwordTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isActiveBox)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(clearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(304, Short.MAX_VALUE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "User List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 102, 153))); // NOI18N

        userDetailsTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "User Id", "Employee Id", "User Name", "Is Active"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userDetailsTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userDetailsTblMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(userDetailsTbl);
        if (userDetailsTbl.getColumnModel().getColumnCount() > 0) {
            userDetailsTbl.getColumnModel().getColumn(0).setMinWidth(0);
            userDetailsTbl.getColumnModel().getColumn(0).setPreferredWidth(0);
            userDetailsTbl.getColumnModel().getColumn(0).setMaxWidth(0);
            userDetailsTbl.getColumnModel().getColumn(1).setMinWidth(0);
            userDetailsTbl.getColumnModel().getColumn(1).setPreferredWidth(0);
            userDetailsTbl.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1037, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBtnActionPerformed
        saveBtn.setText("Save");
        saveBtn.setBackground(new Color(0, 102, 153)); // Change background color
        saveBtn.setForeground(Color.WHITE);
        userID = 0;
        
        userNameTxt.setText("");
        passwordTxt.setText("");
    }//GEN-LAST:event_clearBtnActionPerformed

    int userID = 0;
    
    private void userDetailsTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userDetailsTblMousePressed
        if (evt.getClickCount() == 2) {
            int selectedRow = userDetailsTbl.getSelectedRow();
            if (selectedRow != -1) {
                saveBtn.setText("Update");
                saveBtn.setBackground(Color.ORANGE); // Change background color
                saveBtn.setForeground(Color.BLACK);  // Change text color

                userNameTxt.setText(userDetailsTbl.getValueAt(selectedRow, 2).toString());
                isActiveBox.setSelected(Boolean.parseBoolean(userDetailsTbl.getValueAt(selectedRow, 3).toString()));
                
                userID = Integer.parseInt(userDetailsTbl.getValueAt(selectedRow, 0).toString());
            }
        }
    }//GEN-LAST:event_userDetailsTblMousePressed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        int empId = 0;
        int roleId = 0;
        
        for(EmployeeManagementDto dto : employeeManagementDtos){
            if(dto.getName().equals(employeeCmb.getSelectedItem().toString())){
                empId = dto.getEmployeeId();
            }
        }
            
        for(UserRoleDto dto : userRoleDtos){
            if(dto.getRoleName().equals(userRoleCmb.getSelectedItem().toString())){
                roleId = dto.getUserRoleId();
            }
        }
            
        if (saveBtn.getText() == "Save") {
            //Save  
            UserDto userDto = new UserDto();
            userDto.setEmployeeId(empId);
            userDto.setRoleId(roleId);
            userDto.setPassword(passwordTxt.getText());
            userDto.setUserName(userNameTxt.getText());
            if (isActiveBox.isSelected() == true) {
                userDto.setStatus(1);
            }else{
                userDto.setStatus(0);
            }
            userDto.setVisible(1);
            userDto.setToken("");
            
            try {
                userAcountManagementController.saveUser(userDto);
            } catch (Exception ex) {
                Logger.getLogger(UserAccountManagement.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else {
            //Update
            if (passwordTxt.getText().equals("")) {
                System.out.println("Empty");
                
                UserDto userDto = new UserDto();
                userDto.setUserId(userID);
                userDto.setEmployeeId(empId);
                userDto.setRoleId(roleId);
                userDto.setPassword(passwordTxt.getText());
                userDto.setUserName(userNameTxt.getText());
                if (isActiveBox.isSelected() == true) {
                    userDto.setStatus(1);
                }else{
                    userDto.setStatus(0);
                }
                userDto.setVisible(1);
                userDto.setToken("");
                
                try {
                    userAcountManagementController.updateUser(userDto);
                } catch (Exception ex) {
                    Logger.getLogger(UserAccountManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                System.out.println("Not Empty");
                
                UserDto userDto = new UserDto();
                userDto.setUserId(userID);
                userDto.setEmployeeId(empId);
                userDto.setRoleId(roleId);
                userDto.setPassword(passwordTxt.getText());
                userDto.setUserName(userNameTxt.getText());
                if (isActiveBox.isSelected() == true) {
                    userDto.setStatus(1);
                }else{
                    userDto.setStatus(0);
                }
                userDto.setVisible(1);
                userDto.setToken("");
                
                try {
                    userAcountManagementController.updateUserWithPassword(userDto);
                } catch (Exception ex) {
                    Logger.getLogger(UserAccountManagement.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        
        loadAllUsers();
    }//GEN-LAST:event_saveBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(UserAccountManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(UserAccountManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(UserAccountManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(UserAccountManagement.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new UserAccountManagement().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton clearBtn;
    private javax.swing.JComboBox<String> employeeCmb;
    private javax.swing.JCheckBox isActiveBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel messageLbl;
    private javax.swing.JPasswordField passwordTxt;
    private org.jdesktop.swingx.JXButton saveBtn;
    private org.jdesktop.swingx.JXTable userDetailsTbl;
    private org.jdesktop.swingx.JXTextField userNameTxt;
    private javax.swing.JComboBox<String> userRoleCmb;
    // End of variables declaration//GEN-END:variables

    private void loadAllUsers() {
        try {
            String quary="WHERE visible=1";
            ArrayList<UserDto> allUsers=userAcountManagementController.getAllUsers(quary);
        
            DefaultTableModel dtm=(DefaultTableModel) userDetailsTbl.getModel();
            dtm.setRowCount(0);
            
            for(UserDto dto: allUsers){
                boolean isActive=false;
                
                if(dto.getStatus()==1){
                    isActive=true;
                }
                Object[] rowData={
                    dto.getUserId(),
                    dto.getEmployeeId(),
                    dto.getUserName(),
                    isActive
                };
                dtm.addRow(rowData);
            }
            
        } catch (Exception ex) {
            Logger.getLogger(UserAccountManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    ArrayList<EmployeeManagementDto> employeeManagementDtos = null;

    private void loadEmployees() {
        try {
            employeeManagementDtos=employeeManagementController.getAllEmployees();
        
            for(EmployeeManagementDto dto: employeeManagementDtos){
                employeeCmb.addItem(dto.getName());
                employeeIds.add(dto.getEmployeeId());
            };
            
        } catch (Exception ex) {
            Logger.getLogger(UserAccountManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    ArrayList<UserRoleDto> userRoleDtos = null;
    
    private void loadUserRole() {
        try {
            String quary="WHERE status=1";
            userRoleDtos=userRoleController.getAllUserRoles(quary);
        
            for(UserRoleDto dto: userRoleDtos){
                userRoleCmb.addItem(dto.getRoleName());
                userRoleIds.add(dto.getUserRoleId());
            };
            
        } catch (Exception ex) {
            Logger.getLogger(UserAccountManagement.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
