/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unical.pos.view.main;

import java.awt.Color;
import java.awt.Cursor;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.unical.pos.configurations.Configurations;
import net.unical.pos.configurations.Log;
import net.unical.pos.controller.EmployeeManagementController;
import net.unical.pos.controller.UserAccountManagementController;
import net.unical.pos.controller.UserRoleController;
import net.unical.pos.dto.EmployeeManagementDto;
import net.unical.pos.dto.UserDto;
import net.unical.pos.dto.UserRoleDto;
import net.unical.pos.repository.impl.LoginRepositoryImpl;
import net.unical.pos.view.home.Dashboard;
import org.apache.poi.hssf.record.UserSViewEnd;

/**
 *
 * @author Sanjuka
 */
public class LogInForm extends javax.swing.JFrame {

    /**
     * Creates new form LogInForm
     */
    
    private UserAccountManagementController userAccountManagementController;
    private LoginRepositoryImpl loginRepositoryImpl;
    private UserRoleController userRoleController;
    private EmployeeManagementController employeeManagementController;
    
    public static int userID = 0;
    public static String userName = null;
    public static String userRole = null;
    
    public LogInForm() throws Exception {
        initComponents();
        
        // Styling the button
        jXButton1.setText("Sign In");
        jXButton1.setBorder(new RoundedBorder(20));
        jXButton1.setBackground(new Color(0, 123, 255)); // Bootstrap primary blue
        jXButton1.setForeground(Color.WHITE);
        jXButton1.setFocusPainted(false);
        jXButton1.setContentAreaFilled(true);
        jXButton1.setOpaque(true);
        jXButton1.setCursor(new Cursor(Cursor.HAND_CURSOR));

        // Hover effect
        jXButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jXButton1.setBackground(new Color(0, 105, 217)); // Darker blue on hover
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jXButton1.setBackground(new Color(0, 123, 255)); // Original color
            }
        });
        
        this.setLocationRelativeTo(null);
        
        this.userAccountManagementController=new UserAccountManagementController();
        this.loginRepositoryImpl = new LoginRepositoryImpl();
        this.userRoleController = new UserRoleController();
        this.employeeManagementController = new EmployeeManagementController();
        
        setDefaulUser();
        loadAllUsers();
        lowerCaseCharacters();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        qBtn = new org.jdesktop.swingx.JXButton();
        aBtn = new org.jdesktop.swingx.JXButton();
        zBtn = new org.jdesktop.swingx.JXButton();
        sBtn = new org.jdesktop.swingx.JXButton();
        wBtn = new org.jdesktop.swingx.JXButton();
        eBtn = new org.jdesktop.swingx.JXButton();
        rBtn = new org.jdesktop.swingx.JXButton();
        fBtn = new org.jdesktop.swingx.JXButton();
        dBtn = new org.jdesktop.swingx.JXButton();
        xBtn = new org.jdesktop.swingx.JXButton();
        cBtn = new org.jdesktop.swingx.JXButton();
        jPanel3 = new javax.swing.JPanel();
        jXButton14 = new org.jdesktop.swingx.JXButton();
        jXButton15 = new org.jdesktop.swingx.JXButton();
        jXButton16 = new org.jdesktop.swingx.JXButton();
        jXButton17 = new org.jdesktop.swingx.JXButton();
        jXButton18 = new org.jdesktop.swingx.JXButton();
        jXButton19 = new org.jdesktop.swingx.JXButton();
        jXButton20 = new org.jdesktop.swingx.JXButton();
        jXButton21 = new org.jdesktop.swingx.JXButton();
        jXButton22 = new org.jdesktop.swingx.JXButton();
        jXButton23 = new org.jdesktop.swingx.JXButton();
        jXButton24 = new org.jdesktop.swingx.JXButton();
        jXButton25 = new org.jdesktop.swingx.JXButton();
        mBtn = new org.jdesktop.swingx.JXButton();
        nBtn = new org.jdesktop.swingx.JXButton();
        jBtn = new org.jdesktop.swingx.JXButton();
        kBtn = new org.jdesktop.swingx.JXButton();
        iBtn = new org.jdesktop.swingx.JXButton();
        yBtn = new org.jdesktop.swingx.JXButton();
        uBtn = new org.jdesktop.swingx.JXButton();
        hBtn = new org.jdesktop.swingx.JXButton();
        bBtn = new org.jdesktop.swingx.JXButton();
        vBtn = new org.jdesktop.swingx.JXButton();
        gBtn = new org.jdesktop.swingx.JXButton();
        tBtn = new org.jdesktop.swingx.JXButton();
        dotBtn = new org.jdesktop.swingx.JXButton();
        pBtn = new org.jdesktop.swingx.JXButton();
        oBtn = new org.jdesktop.swingx.JXButton();
        lBtn = new org.jdesktop.swingx.JXButton();
        atBtn = new org.jdesktop.swingx.JXButton();
        oneBtn = new org.jdesktop.swingx.JXButton();
        twoBtn = new org.jdesktop.swingx.JXButton();
        threeBtn = new org.jdesktop.swingx.JXButton();
        fourBtn = new org.jdesktop.swingx.JXButton();
        fiveBtn = new org.jdesktop.swingx.JXButton();
        sixBtn = new org.jdesktop.swingx.JXButton();
        sevenBtn = new org.jdesktop.swingx.JXButton();
        eightBtn = new org.jdesktop.swingx.JXButton();
        nineBtn = new org.jdesktop.swingx.JXButton();
        zeroBtn = new org.jdesktop.swingx.JXButton();
        capsLockBtn = new javax.swing.JToggleButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        userNameTbl = new org.jdesktop.swingx.JXTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        passwordTxt = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocationByPlatform(true);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("/Users/apple/Downloads/Untitled design (7).png")); // NOI18N
        jLabel3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel3.setInheritsPopupMenu(false);
        jLabel3.setMaximumSize(new java.awt.Dimension(500, 500));
        jLabel3.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel3.setPreferredSize(new java.awt.Dimension(100, 100));
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 0, 290, 250));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Password");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, 30));

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        qBtn.setText("q");
        qBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qBtnActionPerformed(evt);
            }
        });
        jPanel2.add(qBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 50, 40));

        aBtn.setText("a");
        aBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aBtnActionPerformed(evt);
            }
        });
        jPanel2.add(aBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 90, 50, 40));

        zBtn.setText("z");
        zBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zBtnActionPerformed(evt);
            }
        });
        jPanel2.add(zBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 50, 40));

        sBtn.setText("s");
        sBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sBtnActionPerformed(evt);
            }
        });
        jPanel2.add(sBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, 50, 40));

        wBtn.setText("w");
        wBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wBtnActionPerformed(evt);
            }
        });
        jPanel2.add(wBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 50, 50, 40));

        eBtn.setText("e");
        eBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eBtnActionPerformed(evt);
            }
        });
        jPanel2.add(eBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, 50, 40));

        rBtn.setText("r");
        rBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnActionPerformed(evt);
            }
        });
        jPanel2.add(rBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 50, 40));

        fBtn.setText("f");
        fBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fBtnActionPerformed(evt);
            }
        });
        jPanel2.add(fBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 50, 40));

        dBtn.setText("d");
        dBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dBtnActionPerformed(evt);
            }
        });
        jPanel2.add(dBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 90, 50, 40));

        xBtn.setText("x");
        xBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                xBtnActionPerformed(evt);
            }
        });
        jPanel2.add(xBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 50, 40));

        cBtn.setText("c");
        cBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cBtnActionPerformed(evt);
            }
        });
        jPanel2.add(cBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 50, 40));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jXButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 50, 40));
        jPanel3.add(jXButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 50, 40));
        jPanel3.add(jXButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 50, 40));
        jPanel3.add(jXButton17, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 100, 50, 40));
        jPanel3.add(jXButton18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 50, 40));
        jPanel3.add(jXButton19, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 50, 40));
        jPanel3.add(jXButton20, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 50, 40));
        jPanel3.add(jXButton21, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 50, 40));
        jPanel3.add(jXButton22, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 50, 40));
        jPanel3.add(jXButton23, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 50, 40));
        jPanel3.add(jXButton24, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 100, 50, 40));
        jPanel3.add(jXButton25, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 50, 40));

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 610, 150));

        mBtn.setText("m");
        mBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mBtnActionPerformed(evt);
            }
        });
        jPanel2.add(mBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 50, 40));

        nBtn.setText("n");
        nBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nBtnActionPerformed(evt);
            }
        });
        jPanel2.add(nBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 50, 40));

        jBtn.setText("j");
        jBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnActionPerformed(evt);
            }
        });
        jPanel2.add(jBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 50, 40));

        kBtn.setText("k");
        kBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kBtnActionPerformed(evt);
            }
        });
        jPanel2.add(kBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, 50, 40));

        iBtn.setText("i");
        iBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iBtnActionPerformed(evt);
            }
        });
        jPanel2.add(iBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 50, 50, 40));

        yBtn.setText("y");
        yBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yBtnActionPerformed(evt);
            }
        });
        jPanel2.add(yBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 50, 50, 40));

        uBtn.setText("u");
        uBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uBtnActionPerformed(evt);
            }
        });
        jPanel2.add(uBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 50, 40));

        hBtn.setText("h");
        hBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hBtnActionPerformed(evt);
            }
        });
        jPanel2.add(hBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 50, 40));

        bBtn.setText("b");
        bBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBtnActionPerformed(evt);
            }
        });
        jPanel2.add(bBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 50, 40));

        vBtn.setText("v");
        vBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vBtnActionPerformed(evt);
            }
        });
        jPanel2.add(vBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 50, 40));

        gBtn.setText("g");
        gBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gBtnActionPerformed(evt);
            }
        });
        jPanel2.add(gBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 90, 50, 40));

        tBtn.setText("t");
        tBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tBtnActionPerformed(evt);
            }
        });
        jPanel2.add(tBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 50, 50, 40));

        dotBtn.setText(".");
        dotBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dotBtnActionPerformed(evt);
            }
        });
        jPanel2.add(dotBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 50, 40));

        pBtn.setText("p");
        pBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pBtnActionPerformed(evt);
            }
        });
        jPanel2.add(pBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 50, 40));

        oBtn.setText("o");
        oBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oBtnActionPerformed(evt);
            }
        });
        jPanel2.add(oBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 50, 40));

        lBtn.setText("l");
        lBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lBtnActionPerformed(evt);
            }
        });
        jPanel2.add(lBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 90, 50, 40));

        atBtn.setText("@");
        atBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atBtnActionPerformed(evt);
            }
        });
        jPanel2.add(atBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 130, 50, 40));

        oneBtn.setText("1");
        oneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oneBtnActionPerformed(evt);
            }
        });
        jPanel2.add(oneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, 50, 40));

        twoBtn.setText("2");
        twoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twoBtnActionPerformed(evt);
            }
        });
        jPanel2.add(twoBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 50, 40));

        threeBtn.setText("3");
        threeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                threeBtnActionPerformed(evt);
            }
        });
        jPanel2.add(threeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 50, 40));

        fourBtn.setText("4");
        fourBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fourBtnActionPerformed(evt);
            }
        });
        jPanel2.add(fourBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 10, 50, 40));

        fiveBtn.setText("5");
        fiveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fiveBtnActionPerformed(evt);
            }
        });
        jPanel2.add(fiveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 50, 40));

        sixBtn.setText("6");
        sixBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sixBtnActionPerformed(evt);
            }
        });
        jPanel2.add(sixBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, 50, 40));

        sevenBtn.setText("7");
        sevenBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sevenBtnActionPerformed(evt);
            }
        });
        jPanel2.add(sevenBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, 50, 40));

        eightBtn.setText("8");
        eightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eightBtnActionPerformed(evt);
            }
        });
        jPanel2.add(eightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 50, 40));

        nineBtn.setText("9");
        nineBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nineBtnActionPerformed(evt);
            }
        });
        jPanel2.add(nineBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 10, 50, 40));

        zeroBtn.setText("0");
        zeroBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zeroBtnActionPerformed(evt);
            }
        });
        jPanel2.add(zeroBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, 50, 40));

        capsLockBtn.setText("CAP");
        capsLockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                capsLockBtnActionPerformed(evt);
            }
        });
        jPanel2.add(capsLockBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, 80));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 610, 180));

        userNameTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "UserId", "User Name", "Token"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        userNameTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                userNameTblMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                userNameTblMousePressed(evt);
            }
        });
        jScrollPane2.setViewportView(userNameTbl);
        if (userNameTbl.getColumnModel().getColumnCount() > 0) {
            userNameTbl.getColumnModel().getColumn(0).setMinWidth(0);
            userNameTbl.getColumnModel().getColumn(0).setPreferredWidth(0);
            userNameTbl.getColumnModel().getColumn(0).setMaxWidth(0);
            userNameTbl.getColumnModel().getColumn(2).setMinWidth(0);
            userNameTbl.getColumnModel().getColumn(2).setPreferredWidth(0);
            userNameTbl.getColumnModel().getColumn(2).setMaxWidth(0);
        }

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 0, 210, 570));

        jLabel4.setBackground(new java.awt.Color(0, 102, 102));
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Powered by HSPC Solutions");
        jLabel4.setOpaque(true);
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 550, 610, 20));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 500, 50, 50));

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 500, 50, 50));

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 80, 60));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 500, 50, 50));

        jXButton1.setBackground(new java.awt.Color(51, 204, 255));
        jXButton1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jXButton1.setText("Sign In");
        jXButton1.setFont(new java.awt.Font("Poppins Light", 0, 18)); // NOI18N
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jXButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 310, 180, 30));

        passwordTxt.setFont(new java.awt.Font("Helvetica Neue", 0, 16)); // NOI18N
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        jPanel1.add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 270, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 822, 574));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setDefaulUser() throws Exception {
        if (userRoleController.isEmpty()) {
            boolean isSaveUser=userRoleController.saveUserRole(
                new UserRoleDto(0,"Super Admin",1,1,1)
            );

            boolean isSaveEmployee=employeeManagementController.saveEmployee(
                    new EmployeeManagementDto(0, "Mr", "Super Admin", "System Maintains","",1,"",0,"","","",1,1)
            );

            UserDto saveUser = userAccountManagementController.saveUser(new UserDto(0, 1,1, "Super Admin", "1234",1,1,""));

            if (isSaveEmployee && isSaveUser && saveUser!=null) {
                JOptionPane.showMessageDialog(this, "Super Admin save successfully.");
            }else {
                JOptionPane.showMessageDialog(this, "Please try agin", "User saving error", JOptionPane.ERROR_MESSAGE);
            }
        }else{
            return;
        }
    }
    
    public String getUserRole(){
        return loginRepositoryImpl.getUserRoleByUserID(userID);
    }
    
    private void loginMethod() throws Exception{
        try {
            if (loginRepositoryImpl.login(userID, passwordTxt.getText())) {
                Dashboard dashboard=new Dashboard();
                dashboard.setVisible(true);
                this.dispose();
            }else{
                JOptionPane.showMessageDialog(this, "Please Check password", "Password Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Please select user", "User Error", JOptionPane.ERROR_MESSAGE);
            Log.error(e, "Not selected user");
        } catch (IllegalArgumentException exception){
            JOptionPane.showMessageDialog(this, "Please enter password", "Password Error", JOptionPane.ERROR_MESSAGE);
            Log.error(exception, "password error");
        }
    }
    
    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        try {
            loginMethod();
        } catch (Exception ex) {
            Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jXButton1ActionPerformed

    private void aBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"A");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"a");
        }
    }//GEN-LAST:event_aBtnActionPerformed

    private void capsLockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_capsLockBtnActionPerformed
        if(capsLockBtn.isSelected()){
            capsLockBtn.setBackground(Color.red);
            capsLockBtn.setForeground(Color.white);
            
            upperCaseCharacters();
            
        }else{
            capsLockBtn.setBackground(new Color(60,63,65));
            capsLockBtn.setForeground(new Color(187,187,187));
            
            lowerCaseCharacters();
        }
    }//GEN-LAST:event_capsLockBtnActionPerformed

    private void oneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oneBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"1");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"1");
        }
    }//GEN-LAST:event_oneBtnActionPerformed

    private void twoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twoBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"2");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"2");
        }
    }//GEN-LAST:event_twoBtnActionPerformed

    private void threeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_threeBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"3");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"3");
        }
    }//GEN-LAST:event_threeBtnActionPerformed

    private void fourBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fourBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"4");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"4");
        }
    }//GEN-LAST:event_fourBtnActionPerformed

    private void fiveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fiveBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"5");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"5");
        }
    }//GEN-LAST:event_fiveBtnActionPerformed

    private void sixBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sixBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"6");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"6");
        }
    }//GEN-LAST:event_sixBtnActionPerformed

    private void sevenBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sevenBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"7");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"7");
        }
    }//GEN-LAST:event_sevenBtnActionPerformed

    private void eightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eightBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"8");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"8");
        }
    }//GEN-LAST:event_eightBtnActionPerformed

    private void nineBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nineBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"9");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"9");
        }
    }//GEN-LAST:event_nineBtnActionPerformed

    private void zeroBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zeroBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"0");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"0");
        }
    }//GEN-LAST:event_zeroBtnActionPerformed

    private void qBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"Q");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"q");
        }
    }//GEN-LAST:event_qBtnActionPerformed

    private void wBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"W");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"w");
        }
    }//GEN-LAST:event_wBtnActionPerformed

    private void eBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"E");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"e");
        }
    }//GEN-LAST:event_eBtnActionPerformed

    private void rBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"R");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"r");
        }
    }//GEN-LAST:event_rBtnActionPerformed

    private void tBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"T");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"t");
        }
    }//GEN-LAST:event_tBtnActionPerformed

    private void yBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"Y");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"y");
        }
    }//GEN-LAST:event_yBtnActionPerformed

    private void uBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"U");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"u");
        }
    }//GEN-LAST:event_uBtnActionPerformed

    private void iBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"I");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"i");
        }
    }//GEN-LAST:event_iBtnActionPerformed

    private void oBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"O");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"o");
        }
    }//GEN-LAST:event_oBtnActionPerformed

    private void pBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"P");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"p");
        }
    }//GEN-LAST:event_pBtnActionPerformed

    private void sBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"S");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"s");
        }
    }//GEN-LAST:event_sBtnActionPerformed

    private void dBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"D");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"d");
        }
    }//GEN-LAST:event_dBtnActionPerformed

    private void fBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"F");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"f");
        }
    }//GEN-LAST:event_fBtnActionPerformed

    private void gBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"G");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"g");
        }
    }//GEN-LAST:event_gBtnActionPerformed

    private void hBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"H");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"h");
        }
    }//GEN-LAST:event_hBtnActionPerformed

    private void jBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"J");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"j");
        }
    }//GEN-LAST:event_jBtnActionPerformed

    private void kBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"K");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"k");
        }
    }//GEN-LAST:event_kBtnActionPerformed

    private void lBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"L");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"l");
        }
    }//GEN-LAST:event_lBtnActionPerformed

    private void zBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"Z");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"z");
        }
    }//GEN-LAST:event_zBtnActionPerformed

    private void xBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_xBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"X");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"x");
        }
    }//GEN-LAST:event_xBtnActionPerformed

    private void cBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"C");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"c");
        }
    }//GEN-LAST:event_cBtnActionPerformed

    private void vBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"V");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"v");
        }
    }//GEN-LAST:event_vBtnActionPerformed

    private void bBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"B");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"b");
        }
    }//GEN-LAST:event_bBtnActionPerformed

    private void nBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"N");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"n");
        }
    }//GEN-LAST:event_nBtnActionPerformed

    private void mBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"M");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"m");
        }
    }//GEN-LAST:event_mBtnActionPerformed

    private void atBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"@");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+"@");
        }
    }//GEN-LAST:event_atBtnActionPerformed

    private void dotBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dotBtnActionPerformed
        if(capsLockBtn.isSelected()){
            String text=passwordTxt.getText();
            passwordTxt.setText(text+".");
        }else{
            String text=passwordTxt.getText();
            passwordTxt.setText(text+".");
        }
    }//GEN-LAST:event_dotBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void userNameTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameTblMouseClicked
        
    }//GEN-LAST:event_userNameTblMouseClicked

    private void userNameTblMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_userNameTblMousePressed
        try {
            if (evt.getClickCount() == 1) {
                userID = Integer.parseInt(userNameTbl.getValueAt(userNameTbl.getSelectedRow(), 0).toString());
                userName = userNameTbl.getValueAt(userNameTbl.getSelectedRow(), 1).toString();
                passwordTxt.requestFocusInWindow();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Please select user agin", "User selecting error", JOptionPane.ERROR_MESSAGE);
            Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, e);
            Log.error(e, e);
        }
    }//GEN-LAST:event_userNameTblMousePressed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        try {
            loginMethod();
        } catch (Exception ex) {
            Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, ex);
            Log.error(ex, ex);
        }
    }//GEN-LAST:event_passwordTxtActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(LogInForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new LogInForm().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton aBtn;
    private org.jdesktop.swingx.JXButton atBtn;
    private org.jdesktop.swingx.JXButton bBtn;
    private org.jdesktop.swingx.JXButton cBtn;
    private javax.swing.JToggleButton capsLockBtn;
    private org.jdesktop.swingx.JXButton dBtn;
    private org.jdesktop.swingx.JXButton dotBtn;
    private org.jdesktop.swingx.JXButton eBtn;
    private org.jdesktop.swingx.JXButton eightBtn;
    private org.jdesktop.swingx.JXButton fBtn;
    private org.jdesktop.swingx.JXButton fiveBtn;
    private org.jdesktop.swingx.JXButton fourBtn;
    private org.jdesktop.swingx.JXButton gBtn;
    private org.jdesktop.swingx.JXButton hBtn;
    private org.jdesktop.swingx.JXButton iBtn;
    private org.jdesktop.swingx.JXButton jBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton14;
    private org.jdesktop.swingx.JXButton jXButton15;
    private org.jdesktop.swingx.JXButton jXButton16;
    private org.jdesktop.swingx.JXButton jXButton17;
    private org.jdesktop.swingx.JXButton jXButton18;
    private org.jdesktop.swingx.JXButton jXButton19;
    private org.jdesktop.swingx.JXButton jXButton20;
    private org.jdesktop.swingx.JXButton jXButton21;
    private org.jdesktop.swingx.JXButton jXButton22;
    private org.jdesktop.swingx.JXButton jXButton23;
    private org.jdesktop.swingx.JXButton jXButton24;
    private org.jdesktop.swingx.JXButton jXButton25;
    private org.jdesktop.swingx.JXButton kBtn;
    private org.jdesktop.swingx.JXButton lBtn;
    private org.jdesktop.swingx.JXButton mBtn;
    private org.jdesktop.swingx.JXButton nBtn;
    private org.jdesktop.swingx.JXButton nineBtn;
    private org.jdesktop.swingx.JXButton oBtn;
    private org.jdesktop.swingx.JXButton oneBtn;
    private org.jdesktop.swingx.JXButton pBtn;
    private javax.swing.JPasswordField passwordTxt;
    private org.jdesktop.swingx.JXButton qBtn;
    private org.jdesktop.swingx.JXButton rBtn;
    private org.jdesktop.swingx.JXButton sBtn;
    private org.jdesktop.swingx.JXButton sevenBtn;
    private org.jdesktop.swingx.JXButton sixBtn;
    private org.jdesktop.swingx.JXButton tBtn;
    private org.jdesktop.swingx.JXButton threeBtn;
    private org.jdesktop.swingx.JXButton twoBtn;
    private org.jdesktop.swingx.JXButton uBtn;
    private org.jdesktop.swingx.JXTable userNameTbl;
    private org.jdesktop.swingx.JXButton vBtn;
    private org.jdesktop.swingx.JXButton wBtn;
    private org.jdesktop.swingx.JXButton xBtn;
    private org.jdesktop.swingx.JXButton yBtn;
    private org.jdesktop.swingx.JXButton zBtn;
    private org.jdesktop.swingx.JXButton zeroBtn;
    // End of variables declaration//GEN-END:variables

    ArrayList<UserDto> userDtos = null;
            
    private void loadAllUsers() {
        try {
            String quary="WHERE status=1 and visible=1";
            userDtos = new ArrayList<>();
            userDtos=userAccountManagementController.getAllUsers(quary);
            
            DefaultTableModel dtm=(DefaultTableModel) userNameTbl.getModel();
            dtm.setRowCount(0);
            
            for(UserDto userDto:userDtos){
                Object[] rowDate={
                    userDto.getUserId(),
                    userDto.getUserName(),
                    userDto.getToken()
                };
                dtm.addRow(rowDate);
            }
        } catch (Exception ex) {
            Logger.getLogger(LogInForm.class.getName()).log(Level.SEVERE, null, ex);
            Log.error(ex, ex);
        }
    }

    private void lowerCaseCharacters() {
        qBtn.setText("q");
        wBtn.setText("w");
        eBtn.setText("e");
        rBtn.setText("r");
        tBtn.setText("t");
        yBtn.setText("y");
        uBtn.setText("u");
        iBtn.setText("i");
        oBtn.setText("o");
        pBtn.setText("p");
        aBtn.setText("a");
        sBtn.setText("s");
        dBtn.setText("d");
        fBtn.setText("f");
        gBtn.setText("g");
        hBtn.setText("h");
        jBtn.setText("j");
        kBtn.setText("k");
        lBtn.setText("l");
        zBtn.setText("z");
        xBtn.setText("x");
        cBtn.setText("c");
        vBtn.setText("v");
        bBtn.setText("b");
        nBtn.setText("n");
        mBtn.setText("m");
    }

    private void upperCaseCharacters() {
        qBtn.setText("Q");
        wBtn.setText("W");
        eBtn.setText("E");
        rBtn.setText("R");
        tBtn.setText("T");
        yBtn.setText("Y");
        uBtn.setText("U");
        iBtn.setText("I");
        oBtn.setText("O");
        pBtn.setText("P");
        aBtn.setText("A");
        sBtn.setText("S");
        dBtn.setText("D");
        fBtn.setText("F");
        gBtn.setText("G");
        hBtn.setText("H");
        jBtn.setText("J");
        kBtn.setText("K");
        lBtn.setText("L");
        zBtn.setText("Z");
        xBtn.setText("X");
        cBtn.setText("C");
        vBtn.setText("V");
        bBtn.setText("B");
        nBtn.setText("N");
        mBtn.setText("M");
    }
}
