/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unical.pos.view.main;

import java.awt.Dimension;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.UIManager;
import net.unical.pos.configurations.ConfigPropertyObject;
import net.unical.pos.configurations.ConfigPropertyReader;

/**
 *
 * @author Sanjuka
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form Main
     */
    public MainForm() {
        initComponents();
//        \net\hspc\pos\imagers\background

        
        try {
            this.setLocationRelativeTo(null);
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
            
        } catch (Exception ex) {
            
        }
        
            URL iconURL = getClass().getResource("/net/hspc/pos/imagers/background/icon.png");
            // iconURL is null when not found
            ImageIcon icon = new ImageIcon(iconURL);
            this.setIconImage(icon.getImage());
            
//            Dimension dd = jPanel1.getSize();
//            jLabel2.setSize(dd.width, dd.height - 20);
//            ImageIcon ic = new ImageIcon(getClass().getResource("/net/hspc/pos/imagers/background/logo.png"));
//                    //ImageIcon ic = new ImageIcon(getClass().getResource("/net/zincat/zinpos/order/images/welcome_eideas.png"));
//                    jLabel2.setIcon(new ImageIcon(ic.getImage().getScaledInstance(dd.width, dd.height, 5)));
//                    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/hspc/pos/imagers/background/logo.png")));
//                    
            Dimension dd = jPanel1.getSize();
            jLabel1.setSize(dd.width, dd.height - 20);
            
            ConfigPropertyReader reader=new ConfigPropertyReader();
            reader.getPropertyConfigurations();
            
            String splash_screen = ConfigPropertyReader.configPropertyObject.getSplash_screen();
            switch (splash_screen) {
                case "1": {
                    ImageIcon ic = new ImageIcon(getClass().getResource("/net/hspc/pos/imagers/background/logo.png"));
                    //ImageIcon ic = new ImageIcon(getClass().getResource("/net/zincat/zinpos/order/images/welcome_eideas.png"));
                    jLabel1.setIcon(new ImageIcon(ic.getImage().getScaledInstance(dd.width, dd.height, 5)));
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/hspc/pos/imagers/background/logo.png")));
                    break;
                }
                case "2": {
                    ImageIcon ic = new ImageIcon(getClass().getResource("/net/hspc/pos/imagers/background/logo.png"));
                    jLabel1.setIcon(new ImageIcon(ic.getImage().getScaledInstance(dd.width, dd.height, 5)));
                    jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/hspc/pos/imagers/background/logo.png")));
                    break;
                }
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(523, 429));

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POS Management System -  V 1.0");

        jLabel2.setOpaque(true);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
