/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unical.pos.view.inventory.store;

import java.util.ArrayList;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.unical.pos.controller.GrnController;
import net.unical.pos.controller.MainItemCategoryController;
import net.unical.pos.controller.MainItemController;
import net.unical.pos.controller.PurchaseOrderController;
import net.unical.pos.controller.StockController;
import net.unical.pos.controller.SubItemCategoryController;
import net.unical.pos.controller.SupplierController;
import net.unical.pos.dto.GoodReceivedNoteDto;
import net.unical.pos.dto.MainItemCategoryDto;
import net.unical.pos.dto.MainItemDto;
import net.unical.pos.dto.PurchaseOrderDetailsDto;
import net.unical.pos.dto.PurchaseOrderDto;
import net.unical.pos.dto.StockDto;
import net.unical.pos.dto.SubItemCategoryDto;
import net.unical.pos.dto.SupplierDto;
import net.unical.pos.view.home.Dashboard;

/**
 *
 * @author Sanjuka
 */
public class GoodReceiveNote extends javax.swing.JInternalFrame {

    private SupplierController supplierController;
    private MainItemCategoryController mainItemCategoryController;
    private SubItemCategoryController subItemCategoryController;
    private PurchaseOrderController purchaseOrderController;
    private MainItemController mainItemController;
    private StockController stockController;
    private GrnController grnController;
    
    private ArrayList<Integer> supplierIds=new ArrayList<>();
    private ArrayList<Integer> mainCategoryIds=new ArrayList<>();
    private ArrayList<Integer> subCategoryIds=new ArrayList<>();
    
    Dashboard dashboard;
    /**
     * Creates new form GRN
     */
    public GoodReceiveNote(Dashboard dashboard) {
        initComponents();
        this.dashboard=dashboard;
        
        this.supplierController=new SupplierController();
        this.mainItemCategoryController=new MainItemCategoryController();
        this.subItemCategoryController=new SubItemCategoryController();
        this.purchaseOrderController=new PurchaseOrderController();
        this.mainItemController=new MainItemController();
        this.stockController=new StockController();
        this.grnController=new GrnController();
        
        loadAllSuppliers();
        loadMainCategory();
        
        currentDatePicker.setDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        poList = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        poListTbl = new org.jdesktop.swingx.JXTable();
        jXButton5 = new org.jdesktop.swingx.JXButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        supplierCmb = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        currentDatePicker = new org.jdesktop.swingx.JXDatePicker();
        jLabel4 = new javax.swing.JLabel();
        invNoTxt = new org.jdesktop.swingx.JXTextField();
        stockCmb = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        mainItemCategoryCmb = new javax.swing.JComboBox<>();
        subItemCategoryCmb = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jXTextField2 = new org.jdesktop.swingx.JXTextField();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        subTotalTxt = new javax.swing.JLabel();
        grandTotalTxt = new javax.swing.JLabel();
        addToStockBtn = new org.jdesktop.swingx.JXButton();
        jXButton3 = new org.jdesktop.swingx.JXButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        grnTbl = new org.jdesktop.swingx.JXTable();

        poList.setTitle("Select Item");

        poList.setAlwaysOnTop(true);

        poList.setMinimumSize(new java.awt.Dimension(700, 450));

        poList.setResizable(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setForeground(new java.awt.Color(255, 255, 255));

        poListTbl.setBackground(new java.awt.Color(255, 255, 255));
        poListTbl.setForeground(new java.awt.Color(0, 0, 0));
        poListTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "PO ID", "PO Code", "Supplier", "Date", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(poListTbl);
        if (poListTbl.getColumnModel().getColumnCount() > 0) {
            poListTbl.getColumnModel().getColumn(0).setMinWidth(0);
            poListTbl.getColumnModel().getColumn(0).setPreferredWidth(0);
            poListTbl.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jXButton5.setBackground(new java.awt.Color(0, 102, 153));
        jXButton5.setForeground(new java.awt.Color(255, 255, 255));
        jXButton5.setText("Select");
        jXButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(248, 248, 248)
                .addComponent(jXButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 155, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jXButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout poListLayout = new javax.swing.GroupLayout(poList.getContentPane());
        poList.getContentPane().setLayout(poListLayout);
        poListLayout.setHorizontalGroup(
            poListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        poListLayout.setVerticalGroup(
            poListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(poListLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Purchase Order Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Supplier");

        supplierCmb.setBackground(new java.awt.Color(255, 255, 255));
        supplierCmb.setForeground(new java.awt.Color(0, 0, 0));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Date");

        currentDatePicker.setForeground(new java.awt.Color(0, 0, 0));
        currentDatePicker.setOpaque(true);

        jLabel4.setForeground(new java.awt.Color(204, 0, 0));
        jLabel4.setText("Invoice No");

        invNoTxt.setBackground(new java.awt.Color(204, 204, 204));
        invNoTxt.setForeground(new java.awt.Color(204, 0, 0));
        invNoTxt.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N

        stockCmb.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Stock Name" }));

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Stock Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(supplierCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(currentDatePicker, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
                    .addComponent(invNoTxt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(stockCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(8, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(supplierCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(currentDatePicker, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(invNoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stockCmb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Item Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(0, 102, 153))); // NOI18N

        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Main Category");

        mainItemCategoryCmb.setBackground(new java.awt.Color(255, 255, 255));
        mainItemCategoryCmb.setForeground(new java.awt.Color(0, 0, 0));
        mainItemCategoryCmb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainItemCategoryCmbActionPerformed(evt);
            }
        });

        subItemCategoryCmb.setBackground(new java.awt.Color(255, 255, 255));
        subItemCategoryCmb.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Sub Category");

        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Item Code | Name");

        jXTextField2.setBackground(new java.awt.Color(255, 255, 255));
        jXTextField2.setForeground(new java.awt.Color(0, 0, 0));

        jXButton1.setBackground(new java.awt.Color(0, 102, 153));
        jXButton1.setForeground(new java.awt.Color(255, 255, 255));
        jXButton1.setText("Search");
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });

        jXButton2.setBackground(new java.awt.Color(153, 0, 0));
        jXButton2.setForeground(new java.awt.Color(255, 255, 255));
        jXButton2.setText("Reset");
        jXButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(subItemCategoryCmb, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(mainItemCategoryCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jXTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mainItemCategoryCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(subItemCategoryCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(7, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 153));
        jLabel3.setText("Sub Total :");

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 102, 153));
        jLabel8.setText("Grand Total :");

        subTotalTxt.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        subTotalTxt.setForeground(new java.awt.Color(0, 102, 153));
        subTotalTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        subTotalTxt.setText("0.00");
        subTotalTxt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        grandTotalTxt.setFont(new java.awt.Font("Dialog", 1, 20)); // NOI18N
        grandTotalTxt.setForeground(new java.awt.Color(0, 102, 153));
        grandTotalTxt.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        grandTotalTxt.setText("0.00");
        grandTotalTxt.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);

        addToStockBtn.setBackground(new java.awt.Color(0, 102, 153));
        addToStockBtn.setForeground(new java.awt.Color(255, 255, 255));
        addToStockBtn.setText("Add to stock");
        addToStockBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToStockBtnActionPerformed(evt);
            }
        });

        jXButton3.setBackground(new java.awt.Color(0, 153, 51));
        jXButton3.setForeground(new java.awt.Color(255, 255, 255));
        jXButton3.setText("Transfer from perchase order");
        jXButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton3ActionPerformed(evt);
            }
        });

        grnTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Po Details Id", "Item Id", "Item Name", "Quantity", "Cost Price", "Unit Price", "Total Price", "Discount Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        grnTbl.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                grnTblPropertyChange(evt);
            }
        });
        grnTbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                grnTblKeyReleased(evt);
            }
        });
        jScrollPane3.setViewportView(grnTbl);
        if (grnTbl.getColumnModel().getColumnCount() > 0) {
            grnTbl.getColumnModel().getColumn(0).setMinWidth(0);
            grnTbl.getColumnModel().getColumn(0).setPreferredWidth(0);
            grnTbl.getColumnModel().getColumn(0).setMaxWidth(0);
            grnTbl.getColumnModel().getColumn(1).setMinWidth(0);
            grnTbl.getColumnModel().getColumn(1).setPreferredWidth(0);
            grnTbl.getColumnModel().getColumn(1).setMaxWidth(0);
        }

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(7, 7, 7)
                        .addComponent(subTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(grandTotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(addToStockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jXButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(subTotalTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(grandTotalTxt))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jXButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addToStockBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXButton1ActionPerformed

    private void jXButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jXButton2ActionPerformed

    private void mainItemCategoryCmbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainItemCategoryCmbActionPerformed
        try {
            subItemCategoryCmb.removeAllItems();
            String mainCategoryName=mainItemCategoryCmb.getSelectedItem().toString();
            ArrayList<SubItemCategoryDto> subItemCategoryDto=subItemCategoryController.searchSubItemCategories(mainCategoryName);
            
            if(mainCategoryName!=null){
                if(subItemCategoryDto.size()==0){
                    subItemCategoryCmb.addItem(null);
                }else{
                    for(SubItemCategoryDto dto : subItemCategoryDto){
                        subItemCategoryCmb.addItem(dto.getSubCategoryName());
                        subCategoryIds.add(dto.getSubItemCategoryId());
                    }
                }
                
            }
        } catch (Exception ex) {
            Logger.getLogger(GoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_mainItemCategoryCmbActionPerformed

    private void jXButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton3ActionPerformed
        loadAllPO();
    }//GEN-LAST:event_jXButton3ActionPerformed

    private void jXButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton5ActionPerformed
        try {
            grnTbl.removeAll();
            Integer poCode=(Integer) poListTbl.getValueAt(poListTbl.getSelectedRow(), 0);
            ArrayList<PurchaseOrderDetailsDto> purchaseOrderDetailsDtos=purchaseOrderController.getAllPurchaseOrderDetails(poCode);
            
            DefaultTableModel dtm=(DefaultTableModel) grnTbl.getModel();
            dtm.setRowCount(0);
            Double subTotal=0.00;
            
            for(PurchaseOrderDetailsDto dto: purchaseOrderDetailsDtos){
                subTotal=subTotal+dto.getLastGrnPrice()*dto.getQty();
                Object[] rowData={
                    dto.getPoDetailsId(),
                    dto.getItemId(),
                    dto.getItemName(),
                    dto.getQty(),
                    dto.getLastGrnPrice(),
                    dto.getLastGrnPrice(),
                    dto.getTotalItemPrice(),
                    0
                };
                dtm.addRow(rowData);
            }
            
            subTotalTxt.setText(subTotal+"");
            grandTotalTxt.setText(subTotal+"");
            
        } catch (Exception ex) {
            Logger.getLogger(GoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        poList.dispose();
        
    }//GEN-LAST:event_jXButton5ActionPerformed

    private void addToStockBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToStockBtnActionPerformed
        try {
            int tableRows = grnTbl.getRowCount();
            boolean result=false;
            
            Integer supplierId=supplierIds.get(supplierCmb.getSelectedIndex());
            GoodReceivedNoteDto grnDto=new GoodReceivedNoteDto(0, 
                        invNoTxt.getText(), 
                        supplierId, 
                        Double.parseDouble(grandTotalTxt.getText()), 
                        Double.parseDouble(grandTotalTxt.getText()), 
                        currentDatePicker.getDate(), 
                        1, 
                        dashboard.CREATED_USER_ID, 
                        1);
                
                Integer grnId=grnController.saveGrn(grnDto);
                
            for (int i = 0; tableRows > i; i++) {
                Integer itemId=(Integer) grnTbl.getValueAt(i, 1);
                Double costPrice=(Double) grnTbl.getValueAt(i, 4);
                Double lastGrnPrice=(Double) grnTbl.getValueAt(i, 4);
                Double qty=(Double) grnTbl.getValueAt(i, 3);
                
                ArrayList<MainItemDto> mainItemDtos=mainItemController.searchAllItems(itemId);
                
                for(MainItemDto itemDto:mainItemDtos){
                    StockDto searchStockDto=stockController.searchStock(itemDto.getItemId());
                    if(searchStockDto!=null){
                            Double fromDBqty=searchStockDto.getQty();
                            StockDto stockDto=new StockDto(
                            0, 
                            grnId,        
                            itemDto.getMainCategoryId(), 
                            itemDto.getSubCataegoryId(),
                            itemDto.getItemId(),
                            itemDto.getBarCode(), 
                            1,
                            "Stock Name", 
                            1,
                            costPrice, 
                            lastGrnPrice, 
                            qty+fromDBqty, 
                            1, 
                            dashboard.CREATED_USER_ID, 
                            1);
                            result=stockController.updateStock(stockDto);
                    }else{
                       StockDto stockDto=new StockDto(
                            0,
                            grnId,   
                            itemDto.getMainCategoryId(), 
                            itemDto.getSubCataegoryId(),
                            itemDto.getItemId(),
                            itemDto.getBarCode(), 
                            1,
                            "Stock Name", 
                            1,
                            costPrice, 
                            lastGrnPrice, 
                            qty, 
                            1, 
                            dashboard.CREATED_USER_ID, 
                            1); 
                       
                            result=stockController.saveStock(stockDto);

                    }
                    
                }
                
            }
            if(result){
                JOptionPane.showMessageDialog(this, "Stock Added Successfully");
                grnTbl.removeAll();
            }else{
                JOptionPane.showMessageDialog(this, "Stock Added Fail");
            }
            
        } catch (Exception ex) {
            Logger.getLogger(GoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
            
    }//GEN-LAST:event_addToStockBtnActionPerformed

    private void grnTblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_grnTblKeyReleased
        int tableRows = grnTbl.getRowCount();
        Double totalPrice=0.00;
        Double totalItemPrice=0.00;
        for (int i = 0; tableRows > i; i++) {
            Double itemPrice=(Double) grnTbl.getValueAt(i, 4);
            Double qty=(Double) grnTbl.getValueAt(i, 3);
            
            totalPrice=totalPrice+itemPrice*qty;
            totalItemPrice=itemPrice*qty;
            
            grnTbl.setValueAt(totalItemPrice, i, 6);
        }

        subTotalTxt.setText(totalPrice+"");
        grandTotalTxt.setText(totalPrice+"");
    }//GEN-LAST:event_grnTblKeyReleased

    private void grnTblPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_grnTblPropertyChange
        
    }//GEN-LAST:event_grnTblPropertyChange

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(GRN.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new GRN().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton addToStockBtn;
    private org.jdesktop.swingx.JXDatePicker currentDatePicker;
    private javax.swing.JLabel grandTotalTxt;
    private org.jdesktop.swingx.JXTable grnTbl;
    private org.jdesktop.swingx.JXTextField invNoTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXButton jXButton3;
    private org.jdesktop.swingx.JXButton jXButton5;
    private org.jdesktop.swingx.JXTextField jXTextField2;
    private javax.swing.JComboBox<String> mainItemCategoryCmb;
    private javax.swing.JDialog poList;
    private org.jdesktop.swingx.JXTable poListTbl;
    private javax.swing.JComboBox<String> stockCmb;
    private javax.swing.JComboBox<String> subItemCategoryCmb;
    private javax.swing.JLabel subTotalTxt;
    private javax.swing.JComboBox<String> supplierCmb;
    // End of variables declaration//GEN-END:variables

    private void loadAllSuppliers() {
        try {
            ArrayList<SupplierDto> supplierDtos=supplierController.getAll();
        
            for(SupplierDto dto: supplierDtos){
                supplierCmb.addItem(dto.getCompanyName());
                supplierIds.add(dto.getSupplierId());
            }
            
        } catch (Exception ex) {
            Logger.getLogger(GoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadMainCategory() {
        try {
            String quary="WHERE status=1 and visible=1";
            ArrayList<MainItemCategoryDto> allCategories=mainItemCategoryController.getAll(quary);
            
            for(MainItemCategoryDto dto: allCategories){
                mainItemCategoryCmb.addItem(dto.getCategoryName());
                mainCategoryIds.add(dto.getMainItemCategeryId());
            }
        } catch (Exception ex) {
            Logger.getLogger(GoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void loadAllPO() {
        try {
            ArrayList<PurchaseOrderDto> allOrderDtos=purchaseOrderController.getAllPurchaseOrder();
            DefaultTableModel dtm=(DefaultTableModel) poListTbl.getModel();
            dtm.setRowCount(0);
            
            for(PurchaseOrderDto dto: allOrderDtos){
                Object[] rowData={
                    dto.getPoId(),
                    dto.getPoCodePrefix(),
                    dto.getSupplierName(),
                    dto.getExpectedDate(),
                    dto.getStatus()
                };
                dtm.addRow(rowData);
            }
            
            poList.setLocationRelativeTo(null);
            poList.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(GoodReceiveNote.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
