/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unical.pos.view.sales;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import net.unical.pos.controller.MainOrderController;
import net.unical.pos.dto.OrderDto;
import net.unical.pos.view.home.Dashboard;

/**
 *
 * @author Sanjuka
 */
public class Sales extends javax.swing.JInternalFrame {

    private MainOrderController mainOrderController;
    
    public DefaultTableModel allResertaions = null;
    /**
     * Creates new form Sales
     */
    private boolean update = false;
    Integer click=0;
    Dashboard dashboard;
    
    public Sales(Dashboard dashboard) {
        this.setTitle("Sales");
        this.dashboard=dashboard;
        initComponents();
        
        this.mainOrderController=new MainOrderController();
        
        allResertaions=(DefaultTableModel) allReservationTbl.getModel();
        
        loadAllOrders();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        posBtn = new org.jdesktop.swingx.JXButton();
        onlineOrdersBtn = new org.jdesktop.swingx.JXButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        allReservationTbl = new org.jdesktop.swingx.JXTable();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jXTable1 = new org.jdesktop.swingx.JXTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jXTable2 = new org.jdesktop.swingx.JXTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jXTable3 = new org.jdesktop.swingx.JXTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jXTable4 = new org.jdesktop.swingx.JXTable();
        onlineOrdersBtn1 = new org.jdesktop.swingx.JXButton();
        onlineOrdersBtn2 = new org.jdesktop.swingx.JXButton();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        jXButton2 = new org.jdesktop.swingx.JXButton();
        jXButton3 = new org.jdesktop.swingx.JXButton();
        jXButton4 = new org.jdesktop.swingx.JXButton();
        onlineOrdersBtn3 = new org.jdesktop.swingx.JXButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        JPanel.setBackground(new java.awt.Color(255, 255, 255));

        posBtn.setBackground(new java.awt.Color(0, 102, 153));
        posBtn.setForeground(new java.awt.Color(255, 255, 255));
        posBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Sales/pos_40px.png"))); // NOI18N
        posBtn.setText("POS");
        posBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        posBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        posBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                posBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                posBtnMouseExited(evt);
            }
        });
        posBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posBtnActionPerformed(evt);
            }
        });

        onlineOrdersBtn.setBackground(new java.awt.Color(0, 102, 153));
        onlineOrdersBtn.setForeground(new java.awt.Color(255, 255, 255));
        onlineOrdersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Sales/online_orders_40px.png"))); // NOI18N
        onlineOrdersBtn.setText("Online Orders");
        onlineOrdersBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        onlineOrdersBtn.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        onlineOrdersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onlineOrdersBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onlineOrdersBtnMouseExited(evt);
            }
        });
        onlineOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineOrdersBtnActionPerformed(evt);
            }
        });

        jTabbedPane1.setForeground(new java.awt.Color(255, 255, 255));

        allReservationTbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Branch", "Order ID", "Bill No", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allReservationTbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                allReservationTblMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(allReservationTbl);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("All Reservations", new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/inventory/icons8-purchase-order-list-35.png")), jPanel5); // NOI18N

        jXTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Bill No", "Price", "Order Type"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jXTable1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("POS", new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Sales/pos_40px.png")), jPanel1); // NOI18N

        jXTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jXTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Online Orders", new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Sales/online_orders_40px.png")), jPanel2); // NOI18N

        jXTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jXTable3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 320, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Banquet", new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-banquet-45.png")), jPanel3); // NOI18N

        jXTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane4.setViewportView(jXTable4);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 829, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("PMS", new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-hotel-room-key-45.png")), jPanel4); // NOI18N

        onlineOrdersBtn1.setBackground(new java.awt.Color(0, 102, 153));
        onlineOrdersBtn1.setForeground(new java.awt.Color(255, 255, 255));
        onlineOrdersBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-banquet-45.png"))); // NOI18N
        onlineOrdersBtn1.setText("Banquet");
        onlineOrdersBtn1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        onlineOrdersBtn1.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        onlineOrdersBtn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onlineOrdersBtn1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onlineOrdersBtn1MouseExited(evt);
            }
        });
        onlineOrdersBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineOrdersBtn1ActionPerformed(evt);
            }
        });

        onlineOrdersBtn2.setBackground(new java.awt.Color(0, 102, 153));
        onlineOrdersBtn2.setForeground(new java.awt.Color(255, 255, 255));
        onlineOrdersBtn2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-hotel-room-key-45.png"))); // NOI18N
        onlineOrdersBtn2.setText("PMS");
        onlineOrdersBtn2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        onlineOrdersBtn2.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        onlineOrdersBtn2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onlineOrdersBtn2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onlineOrdersBtn2MouseExited(evt);
            }
        });
        onlineOrdersBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineOrdersBtn2ActionPerformed(evt);
            }
        });

        jXButton1.setBackground(new java.awt.Color(0, 102, 153));
        jXButton1.setForeground(new java.awt.Color(255, 255, 255));
        jXButton1.setText("Edit Order");

        jXButton2.setBackground(new java.awt.Color(204, 204, 0));
        jXButton2.setForeground(new java.awt.Color(255, 255, 255));
        jXButton2.setText("Print Invoice");

        jXButton3.setBackground(new java.awt.Color(51, 204, 0));
        jXButton3.setForeground(new java.awt.Color(255, 255, 255));
        jXButton3.setText("Payment");

        jXButton4.setBackground(new java.awt.Color(204, 0, 0));
        jXButton4.setForeground(new java.awt.Color(255, 255, 255));
        jXButton4.setText("Cancel Order");

        onlineOrdersBtn3.setBackground(new java.awt.Color(0, 102, 153));
        onlineOrdersBtn3.setForeground(new java.awt.Color(255, 255, 255));
        onlineOrdersBtn3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Sales/icons8-in-transit-45.png"))); // NOI18N
        onlineOrdersBtn3.setText("Delivery Orders");
        onlineOrdersBtn3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        onlineOrdersBtn3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        onlineOrdersBtn3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                onlineOrdersBtn3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                onlineOrdersBtn3MouseExited(evt);
            }
        });
        onlineOrdersBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                onlineOrdersBtn3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jTabbedPane1))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(posBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(onlineOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(onlineOrdersBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(onlineOrdersBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(onlineOrdersBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(posBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onlineOrdersBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onlineOrdersBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onlineOrdersBtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(onlineOrdersBtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jXButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void posBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posBtnActionPerformed
        Sales sales=new Sales(dashboard);
        Order order=new Order(dashboard);
        sales.setVisible(false);
        order.OrderDetails.setVisible(true);  
    }//GEN-LAST:event_posBtnActionPerformed

    private void posBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posBtnMouseEntered
        posBtn.setBackground(new Color(11,125,182));
        posBtn.setVisible(true);
    }//GEN-LAST:event_posBtnMouseEntered

    private void posBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_posBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_posBtnMouseExited

    private void onlineOrdersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineOrdersBtnMouseEntered
        onlineOrdersBtn.setBackground(new Color(11,125,182));
        onlineOrdersBtn.setVisible(true);
    }//GEN-LAST:event_onlineOrdersBtnMouseEntered

    private void onlineOrdersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineOrdersBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_onlineOrdersBtnMouseExited

    private void onlineOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineOrdersBtnActionPerformed
        Sales sales=new Sales(dashboard);
        OnlineOrders onlineOrders=new OnlineOrders(dashboard);
        sales.setVisible(false);
        onlineOrders.setVisible(true);  
    }//GEN-LAST:event_onlineOrdersBtnActionPerformed

    private void onlineOrdersBtn1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineOrdersBtn1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineOrdersBtn1MouseEntered

    private void onlineOrdersBtn1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineOrdersBtn1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineOrdersBtn1MouseExited

    private void onlineOrdersBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineOrdersBtn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineOrdersBtn1ActionPerformed

    private void onlineOrdersBtn2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineOrdersBtn2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineOrdersBtn2MouseEntered

    private void onlineOrdersBtn2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineOrdersBtn2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineOrdersBtn2MouseExited

    private void onlineOrdersBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineOrdersBtn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineOrdersBtn2ActionPerformed

    private void allReservationTblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_allReservationTblMouseClicked
        
    }//GEN-LAST:event_allReservationTblMouseClicked

    private void onlineOrdersBtn3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineOrdersBtn3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineOrdersBtn3MouseEntered

    private void onlineOrdersBtn3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_onlineOrdersBtn3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineOrdersBtn3MouseExited

    private void onlineOrdersBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_onlineOrdersBtn3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_onlineOrdersBtn3ActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Sales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Sales().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPanel;
    private org.jdesktop.swingx.JXTable allReservationTbl;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private org.jdesktop.swingx.JXButton jXButton1;
    private org.jdesktop.swingx.JXButton jXButton2;
    private org.jdesktop.swingx.JXButton jXButton3;
    private org.jdesktop.swingx.JXButton jXButton4;
    private org.jdesktop.swingx.JXTable jXTable1;
    private org.jdesktop.swingx.JXTable jXTable2;
    private org.jdesktop.swingx.JXTable jXTable3;
    private org.jdesktop.swingx.JXTable jXTable4;
    private org.jdesktop.swingx.JXButton onlineOrdersBtn;
    private org.jdesktop.swingx.JXButton onlineOrdersBtn1;
    private org.jdesktop.swingx.JXButton onlineOrdersBtn2;
    private org.jdesktop.swingx.JXButton onlineOrdersBtn3;
    private org.jdesktop.swingx.JXButton posBtn;
    // End of variables declaration//GEN-END:variables
    
    private void btnBackgroundExit(){
        posBtn.setBackground(new Color(0,102,153));
        onlineOrdersBtn.setBackground(new Color(0,102,153));
            
    }

    private void loadAllOrders() {
        try {
            String quary="WHERE status=1";
            ArrayList<OrderDto> orderDtos=mainOrderController.getAllOrders(quary);
            
            DefaultTableModel dtm=(DefaultTableModel) allReservationTbl.getModel();
            dtm.setRowCount(0);
            
            
            Color color=new Color(0,102,153);
            int i=0;
            for(OrderDto orderDto:orderDtos){
                
                
                Object[] rowData={
                    "POS",
                    orderDto.getOrderId(),
                    orderDto.getBillNo(),
                    orderDto.getTotalOrderPrice()
                };
                dtm.addRow(rowData);
                
                if(orderDto.getStatus()==1){
                    ColorRenderer renderer = new ColorRenderer();
                    renderer.setColorForCell(i, i, color);
                    renderer.setColorForCell(1, 1, Color.GREEN);
                    allReservationTbl.setDefaultRenderer(Object.class, renderer);
                }
//                i++;
            }
        } catch (Exception ex) {
            Logger.getLogger(Sales.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    private static class ColorRenderer extends DefaultTableCellRenderer {
        private final Map<String, Color> colorMap = new HashMap<>();


        public void setColorForCell(int row, int col, Color color) {
            colorMap.put(row + ":" + col, color);
        }

    }
}

