/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unical.pos.view.home;

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Font;
import static java.awt.Font.BOLD;
import static java.awt.Font.DIALOG;
import java.awt.Toolkit;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import net.unical.pos.configurations.Configurations;
import net.unical.pos.view.OrderFilter.OrderFilter;
import net.unical.pos.view.Payment.Payment;
import net.unical.pos.view.Reports.Reports;
import net.unical.pos.view.deliveryOrders.DeliveryOrders;
import net.unical.pos.view.employee.Employee;
import net.unical.pos.view.inventory.inventory.Inventory;
import net.unical.pos.view.main.LogInForm;
import net.unical.pos.view.sales.Sales;
/**
 *
 * @author Sanjuka
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    
    public static int CREATED_USER_ID = 1;
    public static String systemMAC = "";
    public static Map<String, String> configValues = new HashMap();
    
    Integer enterd;
    Integer exit;
    public Dashboard() {
        initComponents();
        Dimension fullScreenSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setMinimumSize(fullScreenSize);
        this.setSize(fullScreenSize);
        this.setLocationRelativeTo(null);
        
        setExtendedState(Dashboard.MAXIMIZED_BOTH);
        btnBackgroundExit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        dashboardBtn = new org.jdesktop.swingx.JXButton();
        salesBtn = new org.jdesktop.swingx.JXButton();
        propertyBtn = new org.jdesktop.swingx.JXButton();
        reportsBtn = new org.jdesktop.swingx.JXButton();
        inventoryBtn = new org.jdesktop.swingx.JXButton();
        banquetBtn = new org.jdesktop.swingx.JXButton();
        pmsBtn = new org.jdesktop.swingx.JXButton();
        logoutBtn = new org.jdesktop.swingx.JXButton();
        employeeBtn = new org.jdesktop.swingx.JXButton();
        deliveryOrdersBtn = new org.jdesktop.swingx.JXButton();
        configurationsBtn = new org.jdesktop.swingx.JXButton();
        navBarPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        centerPanel = new javax.swing.JPanel();
        desktopPane = new javax.swing.JDesktopPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("POS");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 77, 128));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        dashboardBtn.setBackground(new java.awt.Color(0, 77, 128));
        dashboardBtn.setForeground(new java.awt.Color(255, 255, 255));
        dashboardBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-dashboard-45.png"))); // NOI18N
        dashboardBtn.setText("Dashboard");
        dashboardBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        dashboardBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        dashboardBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                dashboardBtnMouseExited(evt);
            }
        });
        dashboardBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBtnActionPerformed(evt);
            }
        });
        jPanel3.add(dashboardBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 60));

        salesBtn.setBackground(new java.awt.Color(0, 77, 128));
        salesBtn.setForeground(new java.awt.Color(255, 255, 255));
        salesBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-sales-performance-45.png"))); // NOI18N
        salesBtn.setText("Sales");
        salesBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        salesBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        salesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                salesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                salesBtnMouseExited(evt);
            }
        });
        salesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salesBtnActionPerformed(evt);
            }
        });
        jPanel3.add(salesBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 210, 60));

        propertyBtn.setBackground(new java.awt.Color(0, 77, 128));
        propertyBtn.setForeground(new java.awt.Color(255, 255, 255));
        propertyBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-maintenance-date-45.png"))); // NOI18N
        propertyBtn.setText("Property Management");
        propertyBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        propertyBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        propertyBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                propertyBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                propertyBtnMouseExited(evt);
            }
        });
        propertyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propertyBtnActionPerformed(evt);
            }
        });
        jPanel3.add(propertyBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 210, 60));

        reportsBtn.setBackground(new java.awt.Color(0, 77, 128));
        reportsBtn.setForeground(new java.awt.Color(255, 255, 255));
        reportsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-business-report-45.png"))); // NOI18N
        reportsBtn.setText("Reports");
        reportsBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        reportsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        reportsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                reportsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                reportsBtnMouseExited(evt);
            }
        });
        reportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsBtnActionPerformed(evt);
            }
        });
        jPanel3.add(reportsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 210, 60));

        inventoryBtn.setBackground(new java.awt.Color(0, 77, 128));
        inventoryBtn.setForeground(new java.awt.Color(255, 255, 255));
        inventoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/inventory-45.png"))); // NOI18N
        inventoryBtn.setText("Inventory");
        inventoryBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        inventoryBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        inventoryBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                inventoryBtnMouseExited(evt);
            }
        });
        inventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inventoryBtnActionPerformed(evt);
            }
        });
        jPanel3.add(inventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 210, 60));

        banquetBtn.setBackground(new java.awt.Color(0, 77, 128));
        banquetBtn.setForeground(new java.awt.Color(255, 255, 255));
        banquetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-payment-35.png"))); // NOI18N
        banquetBtn.setText("Payment");
        banquetBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        banquetBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        banquetBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                banquetBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                banquetBtnMouseExited(evt);
            }
        });
        banquetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                banquetBtnActionPerformed(evt);
            }
        });
        jPanel3.add(banquetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 210, 60));

        pmsBtn.setBackground(new java.awt.Color(0, 77, 128));
        pmsBtn.setForeground(new java.awt.Color(255, 255, 255));
        pmsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-hotel-room-key-45.png"))); // NOI18N
        pmsBtn.setText("PMS");
        pmsBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        pmsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        pmsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pmsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pmsBtnMouseExited(evt);
            }
        });
        pmsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pmsBtnActionPerformed(evt);
            }
        });
        jPanel3.add(pmsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, 210, 60));

        logoutBtn.setBackground(new java.awt.Color(0, 77, 128));
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-exit-45.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        logoutBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutBtnMouseExited(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jPanel3.add(logoutBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 600, 210, 60));

        employeeBtn.setBackground(new java.awt.Color(0, 77, 128));
        employeeBtn.setForeground(new java.awt.Color(255, 255, 255));
        employeeBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/employee-45.png"))); // NOI18N
        employeeBtn.setText("Employee");
        employeeBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        employeeBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        employeeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                employeeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                employeeBtnMouseExited(evt);
            }
        });
        employeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeeBtnActionPerformed(evt);
            }
        });
        jPanel3.add(employeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 210, 60));

        deliveryOrdersBtn.setBackground(new java.awt.Color(0, 77, 128));
        deliveryOrdersBtn.setForeground(new java.awt.Color(255, 255, 255));
        deliveryOrdersBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Sales/icons8-in-transit-45.png"))); // NOI18N
        deliveryOrdersBtn.setText("Delivery Orders");
        deliveryOrdersBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        deliveryOrdersBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        deliveryOrdersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deliveryOrdersBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deliveryOrdersBtnMouseExited(evt);
            }
        });
        deliveryOrdersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deliveryOrdersBtnActionPerformed(evt);
            }
        });
        jPanel3.add(deliveryOrdersBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 180, 210, 60));

        configurationsBtn.setBackground(new java.awt.Color(0, 77, 128));
        configurationsBtn.setForeground(new java.awt.Color(255, 255, 255));
        configurationsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/net/unical/pos/imagers/Dashboard/icons8-filter-45.png"))); // NOI18N
        configurationsBtn.setText("  Filter Order");
        configurationsBtn.setFont(new java.awt.Font("Dialog", 1, 15)); // NOI18N
        configurationsBtn.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        configurationsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                configurationsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                configurationsBtnMouseExited(evt);
            }
        });
        configurationsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationsBtnActionPerformed(evt);
            }
        });
        jPanel3.add(configurationsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 210, 60));

        navBarPanel.setBackground(new java.awt.Color(0, 102, 153));

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel12.setBackground(new java.awt.Color(204, 204, 204));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("User Name");

        jLabel17.setBackground(new java.awt.Color(204, 204, 204));
        jLabel17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("March / 31");

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("18.00 PM");

        jLabel13.setBackground(new java.awt.Color(0, 102, 102));
        jLabel13.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(204, 204, 0));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("UNICAL");
        jLabel13.setOpaque(true);

        javax.swing.GroupLayout navBarPanelLayout = new javax.swing.GroupLayout(navBarPanel);
        navBarPanel.setLayout(navBarPanelLayout);
        navBarPanelLayout.setHorizontalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        navBarPanelLayout.setVerticalGroup(
            navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(navBarPanelLayout.createSequentialGroup()
                .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(navBarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, navBarPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, navBarPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, navBarPanelLayout.createSequentialGroup()
                            .addGap(6, 6, 6)
                            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, navBarPanelLayout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        centerPanel.setBackground(new java.awt.Color(0, 102, 102));

        desktopPane.setBackground(new java.awt.Color(255, 255, 255));
        desktopPane.setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("Processing");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("0");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(23, 23, 23))
        );

        jPanel5.setBackground(new java.awt.Color(153, 0, 0));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Fail to deliver");

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("0");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(166, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(182, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(553, Short.MAX_VALUE))
        );

        desktopPane.add(jPanel1, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout centerPanelLayout = new javax.swing.GroupLayout(centerPanel);
        centerPanel.setLayout(centerPanelLayout);
        centerPanelLayout.setHorizontalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane)
        );
        centerPanelLayout.setVerticalGroup(
            centerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(navBarPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(navBarPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(centerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dashboardBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBtnActionPerformed
//        Dashboard dashboard = new Dashboard(this);
//        desktopPane.add(dashboard);
//        Dimension d = desktopPane.getSize();
//        dashboard.setLayer(desktopPane.POPUP_LAYER);
//        dashboard.setSize(d);
//        dashboard.setVisible(true);
    }//GEN-LAST:event_dashboardBtnActionPerformed

    private void propertyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propertyBtnActionPerformed
        
    }//GEN-LAST:event_propertyBtnActionPerformed

    private void employeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeeBtnActionPerformed
        Employee employee= new Employee(this);
        desktopPane.add(employee);
        Dimension d = desktopPane.getSize();
        employee.setLayer(desktopPane.POPUP_LAYER);
        employee.setSize(d);
        employee.setVisible(true);
    }//GEN-LAST:event_employeeBtnActionPerformed

    private void reportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsBtnActionPerformed
        Reports reports = new Reports(this);
        desktopPane.add(reports);
        Dimension d = desktopPane.getSize();
        reports.setLayer(desktopPane.POPUP_LAYER);
        reports.setSize(d);
        reports.setVisible(true);
    }//GEN-LAST:event_reportsBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        LogInForm logInForm=new LogInForm();
        logInForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void dashboardBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseClicked
       
    }//GEN-LAST:event_dashboardBtnMouseClicked

    private void dashboardBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseEntered
        dashboardBtn.setBackground(new Color(11,125,182));
        dashboardBtn.setVisible(true);
    }//GEN-LAST:event_dashboardBtnMouseEntered

    private void salesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesBtnMouseEntered
        salesBtn.setBackground(new Color(11,125,182));
        salesBtn.setVisible(true);
    }//GEN-LAST:event_salesBtnMouseEntered

    private void propertyBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertyBtnMouseEntered
        propertyBtn.setBackground(new Color(11,125,182));
        propertyBtn.setVisible(true);
    }//GEN-LAST:event_propertyBtnMouseEntered

    private void employeeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeBtnMouseEntered
        employeeBtn.setBackground(new Color(11,125,182));
        employeeBtn.setVisible(true);
    }//GEN-LAST:event_employeeBtnMouseEntered

    private void reportsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsBtnMouseEntered
        reportsBtn.setBackground(new Color(11,125,182));
        reportsBtn.setVisible(true);
    }//GEN-LAST:event_reportsBtnMouseEntered

    private void logoutBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseEntered
        logoutBtn.setBackground(new Color(11,125,182));
        setVisible(true);
    }//GEN-LAST:event_logoutBtnMouseEntered

    private void dashboardBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dashboardBtnMouseExited
        btnBackgroundExit();        
    }//GEN-LAST:event_dashboardBtnMouseExited

    private void salesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_salesBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_salesBtnMouseExited

    private void propertyBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_propertyBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_propertyBtnMouseExited

    private void employeeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_employeeBtnMouseExited

    private void reportsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_reportsBtnMouseExited
       btnBackgroundExit();
    }//GEN-LAST:event_reportsBtnMouseExited

    private void logoutBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_logoutBtnMouseExited

    private void salesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salesBtnActionPerformed
        Sales sales=new Sales(this);
        desktopPane.add(sales);
        Dimension d = desktopPane.getSize();
        sales.setLayer(desktopPane.POPUP_LAYER);
        sales.setSize(d);
        sales.setVisible(true);
    }//GEN-LAST:event_salesBtnActionPerformed

    private void inventoryBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseEntered
        inventoryBtn.setBackground(new Color(11,125,182));
        setVisible(true);
    }//GEN-LAST:event_inventoryBtnMouseEntered

    private void inventoryBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_inventoryBtnMouseExited

    private void inventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inventoryBtnActionPerformed
        Inventory inventory = new Inventory(this);
        desktopPane.add(inventory);
        Dimension d = desktopPane.getSize();
        inventory.setLayer(desktopPane.POPUP_LAYER);
        inventory.setSize(d);
        inventory.setVisible(true);
    }//GEN-LAST:event_inventoryBtnActionPerformed

    private void banquetBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banquetBtnMouseEntered
        banquetBtn.setBackground(new Color(11,125,182));
        setVisible(true);
    }//GEN-LAST:event_banquetBtnMouseEntered

    private void banquetBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_banquetBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_banquetBtnMouseExited

    private void banquetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_banquetBtnActionPerformed
        Payment orderFilter;
        try {
            orderFilter = new Payment(this);
            desktopPane.add(orderFilter);
            Dimension d = desktopPane.getSize();
            orderFilter.setLayer(desktopPane.POPUP_LAYER);
            orderFilter.setSize(d);
            orderFilter.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_banquetBtnActionPerformed

    private void pmsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmsBtnMouseEntered
        pmsBtn.setBackground(new Color(11,125,182));
        setVisible(true);
    }//GEN-LAST:event_pmsBtnMouseEntered

    private void pmsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pmsBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_pmsBtnMouseExited

    private void pmsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pmsBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pmsBtnActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        
    }//GEN-LAST:event_formWindowClosed

    private void configurationsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationsBtnMouseEntered
        configurationsBtn.setBackground(new Color(11,125,182));
        setVisible(true);
    }//GEN-LAST:event_configurationsBtnMouseEntered

    private void configurationsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_configurationsBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_configurationsBtnMouseExited

    private void configurationsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationsBtnActionPerformed
        OrderFilter orderFilter;
        try {
            orderFilter = new OrderFilter(this);
            desktopPane.add(orderFilter);
            Dimension d = desktopPane.getSize();
            orderFilter.setLayer(desktopPane.POPUP_LAYER);
            orderFilter.setSize(d);
            orderFilter.setVisible(true);
        } catch (Exception ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_configurationsBtnActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        int dialogResult = JOptionPane.showConfirmDialog(this, Configurations.SYS_EXIT_BUTTON_CONFIRMATION.getConfigValue(), Configurations.SYS_EXIT_BUTTON_CONFIRMATION_TITLE.getConfigValue(), JOptionPane.YES_NO_OPTION);
        if (dialogResult == 0) {
            System.exit(0);
        } else {
            // do nothing
        }
    }//GEN-LAST:event_formWindowClosing

    private void deliveryOrdersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryOrdersBtnMouseEntered
        deliveryOrdersBtn.setBackground(new Color(11,125,182));
        setVisible(true);
    }//GEN-LAST:event_deliveryOrdersBtnMouseEntered

    private void deliveryOrdersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deliveryOrdersBtnMouseExited
        btnBackgroundExit();
    }//GEN-LAST:event_deliveryOrdersBtnMouseExited

    private void deliveryOrdersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deliveryOrdersBtnActionPerformed
        DeliveryOrders deliveryOrders;
        try {
            deliveryOrders = new DeliveryOrders(this);
            desktopPane.add(deliveryOrders);
            Dimension d = desktopPane.getSize();
            deliveryOrders.setLayer(desktopPane.POPUP_LAYER);
            deliveryOrders.setSize(d);
            deliveryOrders.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(Dashboard.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_deliveryOrdersBtnActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Dashboard().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton banquetBtn;
    private javax.swing.JPanel centerPanel;
    private org.jdesktop.swingx.JXButton configurationsBtn;
    private org.jdesktop.swingx.JXButton dashboardBtn;
    private org.jdesktop.swingx.JXButton deliveryOrdersBtn;
    public javax.swing.JDesktopPane desktopPane;
    private org.jdesktop.swingx.JXButton employeeBtn;
    private org.jdesktop.swingx.JXButton inventoryBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private org.jdesktop.swingx.JXButton logoutBtn;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel navBarPanel;
    private org.jdesktop.swingx.JXButton pmsBtn;
    private org.jdesktop.swingx.JXButton propertyBtn;
    private org.jdesktop.swingx.JXButton reportsBtn;
    private org.jdesktop.swingx.JXButton salesBtn;
    // End of variables declaration//GEN-END:variables
    
    private void btnBackgroundEnterd(){
        dashboardBtn.setBackground(new Color(255, 204, 0));
        salesBtn.setBackground(new Color(255, 204, 0));
        propertyBtn.setBackground(new Color(255, 204, 0));
        employeeBtn.setBackground(new Color(255, 204, 0));
        reportsBtn.setBackground(new Color(255, 204, 0));
        logoutBtn.setBackground(new Color(255, 204, 0));
    }
    
    private void btnBackgroundExit(){
        dashboardBtn.setBackground(new Color(0, 77, 128));
        salesBtn.setBackground(new Color(0, 77, 128));
        inventoryBtn.setBackground(new Color(0, 77, 128));
        deliveryOrdersBtn.setBackground(new Color(0, 77, 128));
        banquetBtn.setBackground(new Color(0, 77, 128));
        pmsBtn.setBackground(new Color(0, 77, 128));
        propertyBtn.setBackground(new Color(0, 77, 128));
        employeeBtn.setBackground(new Color(0, 77, 128));
        reportsBtn.setBackground(new Color(0, 77, 128));
        configurationsBtn.setBackground(new Color(0, 77, 128));
        logoutBtn.setBackground(new Color(0, 77, 128));    
    }
}
