/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package net.unical.pos.view.Configuration;

import net.unical.pos.view.Inquiry.*;
import net.unical.pos.view.employee.*;
import java.awt.Dimension;
import net.unical.pos.view.home.Dashboard;

/**
 *
 * @author Sanjuka
 */
public class Configuration extends javax.swing.JInternalFrame {

    /**
     * Creates new form Employee
     */
    Dashboard dashboard;
    public Configuration(Dashboard dashboard) {
        this.dashboard=dashboard;
        this.setTitle("Configuration");
        initComponents();
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuration Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(0, 102, 153))); // NOI18N
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jXButton1 = new org.jdesktop.swingx.JXButton();
        btnManageCourierCompany = new org.jdesktop.swingx.JXButton();
        btnManageCourierBranch = new org.jdesktop.swingx.JXButton();
        btnManageStatus = new org.jdesktop.swingx.JXButton();
        btnManageStatusType = new org.jdesktop.swingx.JXButton();
        btnManageUserAuth = new org.jdesktop.swingx.JXButton();
        btnManageOrderType = new org.jdesktop.swingx.JXButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Configuration Management", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(0, 102, 153))); // NOI18N
        jPanel2.setFocusable(false);

        jXButton1.setBackground(new java.awt.Color(0, 102, 153));
        jXButton1.setForeground(new java.awt.Color(255, 255, 255));
        jXButton1.setText("Manage Resons");
        jXButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jXButton1ActionPerformed(evt);
            }
        });

        btnManageCourierCompany.setBackground(new java.awt.Color(0, 102, 153));
        btnManageCourierCompany.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCourierCompany.setText("Manage Courier Company");
        btnManageCourierCompany.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourierCompanyActionPerformed(evt);
            }
        });

        btnManageCourierBranch.setBackground(new java.awt.Color(0, 102, 153));
        btnManageCourierBranch.setForeground(new java.awt.Color(255, 255, 255));
        btnManageCourierBranch.setText("Manage Courier Branch");
        btnManageCourierBranch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageCourierBranchActionPerformed(evt);
            }
        });

        btnManageStatus.setBackground(new java.awt.Color(0, 102, 153));
        btnManageStatus.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStatus.setText("Manage Status Reg");
        btnManageStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStatusActionPerformed(evt);
            }
        });

        btnManageStatusType.setBackground(new java.awt.Color(0, 102, 153));
        btnManageStatusType.setForeground(new java.awt.Color(255, 255, 255));
        btnManageStatusType.setText("Manage Status Type");
        btnManageStatusType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStatusTypeActionPerformed(evt);
            }
        });

        btnManageUserAuth.setBackground(new java.awt.Color(0, 102, 153));
        btnManageUserAuth.setForeground(new java.awt.Color(255, 255, 255));
        btnManageUserAuth.setText("Manage User Auth");
        btnManageUserAuth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageUserAuthActionPerformed(evt);
            }
        });

        btnManageOrderType.setBackground(new java.awt.Color(0, 102, 153));
        btnManageOrderType.setForeground(new java.awt.Color(255, 255, 255));
        btnManageOrderType.setText("Manage Order Type");
        btnManageOrderType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageOrderTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnManageCourierCompany, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jXButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(btnManageCourierBranch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageStatus, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageStatusType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageUserAuth, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManageOrderType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jXButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageCourierCompany, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageCourierBranch, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnManageStatusType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageUserAuth, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnManageOrderType, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 515, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.getAccessibleContext().setAccessibleName("Inquiry Management");
        jPanel2.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("");

        getAccessibleContext().setAccessibleName("Inquiry Management");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageCourierCompanyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourierCompanyActionPerformed
        ManageCourierCompany manageCourierCompany = new ManageCourierCompany(dashboard);
        dashboard.desktopPane.add(manageCourierCompany);
        Dimension d = dashboard.desktopPane.getSize();
        manageCourierCompany.setLayer(dashboard.desktopPane.POPUP_LAYER);
        manageCourierCompany.setSize(d);
        manageCourierCompany.setVisible(true);
    }//GEN-LAST:event_btnManageCourierCompanyActionPerformed

    private void jXButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jXButton1ActionPerformed
        ManageReson manageReson = new ManageReson(dashboard);
        dashboard.desktopPane.add(manageReson);
        Dimension d = dashboard.desktopPane.getSize();
        manageReson.setLayer(dashboard.desktopPane.POPUP_LAYER);
        manageReson.setSize(d);
        manageReson.setVisible(true);
    }//GEN-LAST:event_jXButton1ActionPerformed

    private void btnManageCourierBranchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageCourierBranchActionPerformed
        ManageCourierBranch manageCourierBranch = new ManageCourierBranch(dashboard);
        dashboard.desktopPane.add(manageCourierBranch);
        Dimension d = dashboard.desktopPane.getSize();
        manageCourierBranch.setLayer(dashboard.desktopPane.POPUP_LAYER);
        manageCourierBranch.setSize(d);
        manageCourierBranch.setVisible(true);
    }//GEN-LAST:event_btnManageCourierBranchActionPerformed

    private void btnManageStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStatusActionPerformed
        ManageStatus manageStatus = new ManageStatus(dashboard);
        dashboard.desktopPane.add(manageStatus);
        Dimension d = dashboard.desktopPane.getSize();
        manageStatus.setLayer(dashboard.desktopPane.POPUP_LAYER);
        manageStatus.setSize(d);
        manageStatus.setVisible(true);
    }//GEN-LAST:event_btnManageStatusActionPerformed

    private void btnManageStatusTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStatusTypeActionPerformed
        ManageStatusType manageStatusType = new ManageStatusType(dashboard);
        dashboard.desktopPane.add(manageStatusType);
        Dimension d = dashboard.desktopPane.getSize();
        manageStatusType.setLayer(dashboard.desktopPane.POPUP_LAYER);
        manageStatusType.setSize(d);
        manageStatusType.setVisible(true);
    }//GEN-LAST:event_btnManageStatusTypeActionPerformed

    private void btnManageUserAuthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageUserAuthActionPerformed
        ManageUserAuth manageUserAuth = new ManageUserAuth(dashboard);
        dashboard.desktopPane.add(manageUserAuth);
        Dimension d = dashboard.desktopPane.getSize();
        manageUserAuth.setLayer(dashboard.desktopPane.POPUP_LAYER);
        manageUserAuth.setSize(d);
        manageUserAuth.setVisible(true);
    }//GEN-LAST:event_btnManageUserAuthActionPerformed

    private void btnManageOrderTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageOrderTypeActionPerformed
        // TODO add your handling code here:
        ManageOrderType manageOrderType = new ManageOrderType();
        dashboard.desktopPane.add(manageOrderType);
         Dimension d = dashboard.desktopPane.getSize();
        manageOrderType.setLayer(dashboard.desktopPane.POPUP_LAYER);
        manageOrderType.setSize(d);
        manageOrderType.setVisible(true);
        
    }//GEN-LAST:event_btnManageOrderTypeActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Employee().setVisible(true);
//            }
//        });
//    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.jdesktop.swingx.JXButton btnManageCourierBranch;
    private org.jdesktop.swingx.JXButton btnManageCourierCompany;
    private org.jdesktop.swingx.JXButton btnManageOrderType;
    private org.jdesktop.swingx.JXButton btnManageStatus;
    private org.jdesktop.swingx.JXButton btnManageStatusType;
    private org.jdesktop.swingx.JXButton btnManageUserAuth;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private org.jdesktop.swingx.JXButton jXButton1;
    // End of variables declaration//GEN-END:variables

}
