/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package net.unical.pos.view.Configuration;

import java.awt.Color;
import net.unical.pos.view.Inquiry.*;
import java.awt.Dimension;
import java.sql.Timestamp;
import net.unical.pos.view.Payment.*;
import net.unical.pos.view.OrderFilter.*;
import java.text.DateFormat;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.unical.pos.view.home.Dashboard;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.unical.pos.controller.DeliveryOrderController;
import net.unical.pos.controller.PaymentTypesController;
import net.unical.pos.dto.PaymentTypeDto;
import net.unical.pos.log.Log;
import net.unical.pos.model.DeliveryOrder;
import net.unical.pos.model.DeliveryOrderAmounts;
import net.unical.pos.model.InquiryModel;
import net.unical.pos.model.ResonModel;
import net.unical.pos.model.UserAuth;
import net.unical.pos.model.AuthModule;
import net.unical.pos.model.AuthModuleWise;
import net.unical.pos.repository.impl.DeliveryOrderRepositoryImpl;
import net.unical.pos.repository.impl.InquiryRepositoryImpl;
import net.unical.pos.repository.impl.ManageUserAuthRepositoryImpl;
import net.unical.pos.repository.impl.PaymentRepositoryImpl;
import net.unical.pos.repository.impl.ResonRepositoryImpl;
import net.unical.pos.view.deliveryOrders.DeliveryOrders;

/**
 *
 * @author apple
 */
public class ManageUserAuth extends JInternalFrame {
    private ManageUserAuthRepositoryImpl manageUserAuthRepositoryImpl;

    /**
     * Creates new form OrderFilter
     */
    public ManageUserAuth() {
        initComponents();
        setTitle("Manage User Auth");
        setClosable(true);
        setMaximizable(true);
        setIconifiable(true);
        setResizable(true);
        pack();
        desktopPane = new javax.swing.JDesktopPane();
    }

    public ManageUserAuth(Dashboard dashboard) {
        this();
        this.manageUserAuthRepositoryImpl = new ManageUserAuthRepositoryImpl();
        
        getAllResons();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ModelOptions = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        btnSave = new javax.swing.JButton();
        btnDashboard = new javax.swing.JToggleButton();
        btnDeliveryOrders = new javax.swing.JToggleButton();
        btnInquiry = new javax.swing.JToggleButton();
        btnSales = new javax.swing.JToggleButton();
        btnFilterOrder = new javax.swing.JToggleButton();
        btnPMS = new javax.swing.JToggleButton();
        btnInventory = new javax.swing.JToggleButton();
        btnPayment = new javax.swing.JToggleButton();
        btnEmployee = new javax.swing.JToggleButton();
        btnPropertyManagement = new javax.swing.JToggleButton();
        btnConfiguration = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        resonTable = new org.jdesktop.swingx.JXTable();
        jPanel4 = new javax.swing.JPanel();

        ModelOptions.setAlwaysOnTop(true);
        ModelOptions.setResizable(false);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        btnSave.setBackground(new java.awt.Color(51, 153, 0));
        btnSave.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDashboard.setBackground(new java.awt.Color(0, 153, 153));
        btnDashboard.setForeground(new java.awt.Color(255, 255, 255));
        btnDashboard.setText("Dashboard");
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });

        btnDeliveryOrders.setBackground(new java.awt.Color(0, 153, 153));
        btnDeliveryOrders.setForeground(new java.awt.Color(255, 255, 255));
        btnDeliveryOrders.setText("Delivery Orders");

        btnInquiry.setBackground(new java.awt.Color(0, 153, 153));
        btnInquiry.setForeground(new java.awt.Color(255, 255, 255));
        btnInquiry.setText("Inquiry");

        btnSales.setBackground(new java.awt.Color(0, 153, 153));
        btnSales.setForeground(new java.awt.Color(255, 255, 255));
        btnSales.setText("Sales");

        btnFilterOrder.setBackground(new java.awt.Color(0, 153, 153));
        btnFilterOrder.setForeground(new java.awt.Color(255, 255, 255));
        btnFilterOrder.setText("Filter Order");

        btnPMS.setBackground(new java.awt.Color(0, 153, 153));
        btnPMS.setForeground(new java.awt.Color(255, 255, 255));
        btnPMS.setText("PMS");

        btnInventory.setBackground(new java.awt.Color(0, 153, 153));
        btnInventory.setForeground(new java.awt.Color(255, 255, 255));
        btnInventory.setText("Inventory");

        btnPayment.setBackground(new java.awt.Color(0, 153, 153));
        btnPayment.setForeground(new java.awt.Color(255, 255, 255));
        btnPayment.setText("Payment");

        btnEmployee.setBackground(new java.awt.Color(0, 153, 153));
        btnEmployee.setForeground(new java.awt.Color(255, 255, 255));
        btnEmployee.setText("Employee");

        btnPropertyManagement.setBackground(new java.awt.Color(0, 153, 153));
        btnPropertyManagement.setForeground(new java.awt.Color(255, 255, 255));
        btnPropertyManagement.setText("Property Management");

        btnConfiguration.setBackground(new java.awt.Color(0, 153, 153));
        btnConfiguration.setForeground(new java.awt.Color(255, 255, 255));
        btnConfiguration.setText("Configuration");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btnDashboard, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnDeliveryOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(52, 52, 52)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnPMS, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnFilterOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(46, 46, 46)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                            .addComponent(btnPropertyManagement)
                            .addGap(46, 46, 46)
                            .addComponent(btnConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(93, 93, 93)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnDashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(btnDeliveryOrders, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(btnInquiry, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnSales, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(btnFilterOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(36, 36, 36)
                            .addComponent(btnPMS, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnInventory, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(btnEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnPropertyManagement, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnConfiguration, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout ModelOptionsLayout = new javax.swing.GroupLayout(ModelOptions.getContentPane());
        ModelOptions.getContentPane().setLayout(ModelOptionsLayout);
        ModelOptionsLayout.setHorizontalGroup(
            ModelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        ModelOptionsLayout.setVerticalGroup(
            ModelOptionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        resonTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "", "Employee Name", "User Role"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        resonTable.setEditable(false);
        resonTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resonTableMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                resonTableMousePressed(evt);
            }
        });
        resonTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                resonTablePropertyChange(evt);
            }
        });
        resonTable.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                resonTableKeyReleased(evt);
            }
        });
        jScrollPane6.setViewportView(resonTable);
        if (resonTable.getColumnModel().getColumnCount() > 0) {
            resonTable.getColumnModel().getColumn(0).setMinWidth(5);
            resonTable.getColumnModel().getColumn(0).setMaxWidth(5);
        }
        if (resonTable.getColumnModel().getColumnCount() > 0) {
            resonTable.getColumnModel().getColumn(0).setMinWidth(0);
            resonTable.getColumnModel().getColumn(0).setPreferredWidth(0);
            resonTable.getColumnModel().getColumn(0).setMaxWidth(0);
        }

        jPanel4.setBackground(new java.awt.Color(0, 102, 153));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1394, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 21, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 1388, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Integer selectedUserId = null;
    
    public void getAllResons() {
        DefaultTableModel dtm = (DefaultTableModel) resonTable.getModel();
        dtm.setRowCount(0);

        List<UserAuth> userAuths = manageUserAuthRepositoryImpl.getAllUsers();
        for (UserAuth model : userAuths) {
            Object[] row = {
                model.getUser_id(),
                model.getEmp_name(),
                model.getUser_role()
            };
            dtm.addRow(row);
        }

        resonTable.setModel(dtm);
    }

    
    private void resonTableKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_resonTableKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_resonTableKeyReleased

    private void resonTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_resonTablePropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_resonTablePropertyChange

    private void resonTableMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resonTableMousePressed
        if (evt.getClickCount() == 2) {
            int selectedRow = resonTable.getSelectedRow();
            if (selectedRow != -1) {
                selectedUserId = Integer.parseInt(resonTable.getValueAt(selectedRow, 0).toString()); // Assuming reson_id is the 1st column
                String resonText = resonTable.getValueAt(selectedRow, 1).toString();
                
                ModelOptions.setLocationRelativeTo(null);
                ModelOptions.setSize(530, 450);
                ModelOptions.setLocationRelativeTo(null);
                ModelOptions.setTitle("Actions");
                ModelOptions.setVisible(true);
                
                ArrayList<AuthModuleWise> authModuleWises = manageUserAuthRepositoryImpl.getAllModuleWiseByUserID(selectedUserId);
                
                btnDashboard.setSelected(false);
                btnSales.setSelected(false);
                btnInventory.setSelected(false);
                btnDeliveryOrders.setSelected(false);
                btnFilterOrder.setSelected(false);
                btnPayment.setSelected(false);
                btnInquiry.setSelected(false);
                btnPMS.setSelected(false);
                btnEmployee.setSelected(false);
                btnPropertyManagement.setSelected(false);
                btnConfiguration.setSelected(false);

                // Set selected based on module_id
                for (AuthModuleWise auth : authModuleWises) {
                    switch (auth.getModule_id()) {
                        case 1: btnDashboard.setSelected(auth.getStatus() == 1); break;
                        case 2: btnSales.setSelected(auth.getStatus() == 1); break;
                        case 3: btnInventory.setSelected(auth.getStatus() == 1); break;
                        case 4: btnDeliveryOrders.setSelected(auth.getStatus() == 1); break;
                        case 5: btnFilterOrder.setSelected(auth.getStatus() == 1); break;
                        case 6: btnPayment.setSelected(auth.getStatus() == 1); break;
                        case 7: btnInquiry.setSelected(auth.getStatus() == 1); break;
                        case 8: btnPMS.setSelected(auth.getStatus() == 1); break;
                        case 9: btnEmployee.setSelected(auth.getStatus() == 1); break;
                        case 10: btnPropertyManagement.setSelected(auth.getStatus() == 1); break;
                        case 11: btnConfiguration.setSelected(auth.getStatus() == 1); break;
                    }
                }
            }
        }
    }//GEN-LAST:event_resonTableMousePressed

    private void resonTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resonTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resonTableMouseClicked

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        ArrayList<AuthModuleWise> authModuleWise = new ArrayList<>();
        Timestamp now = new Timestamp(System.currentTimeMillis());
        
        authModuleWise.add(0, new AuthModuleWise(0,1,selectedUserId,now,now,btnDashboard.isSelected() == true ? 1:0));
        authModuleWise.add(1, new AuthModuleWise(0,2,selectedUserId,now,now,btnSales.isSelected() == true ? 1:0));
        authModuleWise.add(2, new AuthModuleWise(0,3,selectedUserId,now,now,btnInventory.isSelected() == true ? 1:0));
        authModuleWise.add(3, new AuthModuleWise(0,4,selectedUserId,now,now,btnDeliveryOrders.isSelected() == true ? 1:0));
        authModuleWise.add(4, new AuthModuleWise(0,5,selectedUserId,now,now,btnFilterOrder.isSelected() == true ? 1:0));
        authModuleWise.add(5, new AuthModuleWise(0,6,selectedUserId,now,now,btnPayment.isSelected() == true ? 1:0));
        authModuleWise.add(6, new AuthModuleWise(0,7,selectedUserId,now,now,btnInquiry.isSelected() == true ? 1:0));
        authModuleWise.add(7, new AuthModuleWise(0,8,selectedUserId,now,now,btnPMS.isSelected() == true ? 1:0));
        authModuleWise.add(8, new AuthModuleWise(0,9,selectedUserId,now,now,btnEmployee.isSelected() == true ? 1:0));
        authModuleWise.add(9, new AuthModuleWise(0,10,selectedUserId,now,now,btnPropertyManagement.isSelected() == true ? 1:0));
        authModuleWise.add(10, new AuthModuleWise(0,11,selectedUserId,now,now,btnConfiguration.isSelected() == true ? 1:0));
        
        if (manageUserAuthRepositoryImpl.saveModuleWise(authModuleWise)) {
            ModelOptions.setVisible(false);
            JOptionPane.showMessageDialog(this, "Saved!");
        }else{
            ModelOptions.setVisible(false);
            JOptionPane.showMessageDialog(this, "Error");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageUserAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageUserAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageUserAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageUserAuth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageUserAuth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDialog ModelOptions;
    private javax.swing.JToggleButton btnConfiguration;
    private javax.swing.JToggleButton btnDashboard;
    private javax.swing.JToggleButton btnDeliveryOrders;
    private javax.swing.JToggleButton btnEmployee;
    private javax.swing.JToggleButton btnFilterOrder;
    private javax.swing.JToggleButton btnInquiry;
    private javax.swing.JToggleButton btnInventory;
    private javax.swing.JToggleButton btnPMS;
    private javax.swing.JToggleButton btnPayment;
    private javax.swing.JToggleButton btnPropertyManagement;
    private javax.swing.JToggleButton btnSales;
    private javax.swing.JButton btnSave;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane6;
    private org.jdesktop.swingx.JXTable resonTable;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JDesktopPane desktopPane;

}
